### ISSUE TITLE
HD Conga Parrot doesn't line up

### ISSUE THREAD

**Issue by iantabolt** [jmhobbs/cultofthepartyparrot.com#104]
I love this parrot but unfortunately I think the frame might be too wide.

![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/8b4946ae75c1175a1ff42dac2b34a1afc52a0577/parrots/hd/congaparrot.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/8b4946ae75c1175a1ff42dac2b34a1afc52a0577/parrots/hd/congaparrot.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/8b4946ae75c1175a1ff42dac2b34a1afc52a0577/parrots/hd/congaparrot.gif)

Compare to

![](https://raw.githubusercontent.com/jmhobbs/cultofthepartyparrot.com/master/parrots/congaparrot.gif)![](https://raw.githubusercontent.com/jmhobbs/cultofthepartyparrot.com/master/parrots/congaparrot.gif)![](https://raw.githubusercontent.com/jmhobbs/cultofthepartyparrot.com/master/parrots/congaparrot.gif)![](https://raw.githubusercontent.com/jmhobbs/cultofthepartyparrot.com/master/parrots/congaparrot.gif)

**Comment by jmhobbs** [comment]
YE GADS!
