### ISSUE TITLE
DonutParrot needs to reduce his weight!!!! 

### ISSUE THREAD

**Issue by melinerunen** [jmhobbs/cultofthepartyparrot.com#105]
The donut parrot needs to be smaller than 64kb!!!! Slack requires fit parrots :sadparrot:

**Comment by jmhobbs** [comment]
Well, I mean, the parrot is eating donuts, so...  😉

**Comment by jmhobbs** [comment]
We should also (perhaps) add a unit test that all gifs are under 64kb.

**Comment by melinerunen** [comment]
The parrot needs to exercise !!!!!

By the way, i'm working on a unit test for the weight. We can call it "Biggest Loser parrot"  (?)

**Comment by jmhobbs** [comment]
@melinerunen I actually wrote this up last night, but I'd love your input on the PR, or revisions to that test.
