### ISSUE TITLE
Request: Partyplatypus

### ISSUE THREAD

**Issue by kiwivogel** [jmhobbs/cultofthepartyparrot.com#108]
For obvious reasons :P

**Comment by dnguyenchevy** [comment]
The problem with this... is that it doesn't follow the "Parrot" theme.

**Comment by kiwivogel** [comment]
There is a party nyancat. How does that fit in?

**Comment by dnguyenchevy** [comment]
Can you provide more context on what you consider "party platypus"?

**Comment by erinknight242** [comment]
Perhaps something like: https://ppaas.herokuapp.com/partyparrot?overlay=http://www.eknightmusic.com/images/beak.png&overlayWidth=23&overlayHeight=20&overlayOffsetX=3&overlayOffsetY=-8

**Comment by melinerunen** [comment]
To me is more like a Parrot with beard or a parrot with cold and snorting :P

**Comment by kiwivogel** [comment]
Apparent lack of interest, closing.
