### ISSUE TITLE
We need a jedi parrot!!!

### ISSUE THREAD

**Issue by melinerunen** [jmhobbs/cultofthepartyparrot.com#111]
When I finished seeing the first trailer of the Last Jedi, I realized that we don't have any Jedi parrot!!! 
We have a harry potter but no a Jedi!!!

If someone has enough Force, please do a Jedi parrot. Also a Sith parrot so we can do some kind of parrot battle.

I'm on vacations and I don't have too much internet. 

May the force be with you.

**Comment by jmhobbs** [comment]
Yes please!

**Comment by cavpolloosigu** [comment]
We have one now =)
I think we can close this issue: https://github.com/jmhobbs/cultofthepartyparrot.com/blob/master/parrots/hd/jediparrot.gif

**Comment by jmhobbs** [comment]
Excellent point!  Closed by #145
