### ISSUE TITLE
Reduced Motion?

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#115]
A question from Twitter that I don't know the answer to.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">serious question - is Party Parrot dangerous for epileptics? some of the variations are super super fast, don&#39;t want my emoji to harm anyone</p>&mdash; @jongold (@jongold) <a href="https://twitter.com/jongold/status/857665366553526272">April 27, 2017</a></blockquote>

A relevant article I found; https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity

Unsure how to move forward here, I don't want the website to hurt anyone.  A global pause button would be good, perhaps paused by default.

A warning message in the zip file and repo readme would be good too.

Is there an HTTP client header or anything that signals a request for reduced motion?  I couldn't find anything like that.

Thoughts on things we could do?  Anyone know someone who is an expert in this space we could ask?

**Comment by erinknight242** [comment]
It doesn't look like there's a browser setting yet, but that article does link to a toggle switch you could use: http://codepen.io/nattarnoff/pen/JoMxpK

**Comment by melinerunen** [comment]
Just leaving this... https://www.youtube.com/watch?v=hZzTpjh-NsQ

**Comment by vaicine** [comment]
You could use something like [gifffer](https://github.com/krasimir/gifffer) and not have the gifs play on hover on the website, and also a "play all" button.

**Comment by vaicine** [comment]
You could also use the `prefers-reduced-motion` media query to show the emojis without animation. It has limited support for now https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion
