### ISSUE TITLE
Add parrot-dad

### ISSUE THREAD

**Issue by zachleat** [jmhobbs/cultofthepartyparrot.com#14]
![parrot-dad](https://cloud.githubusercontent.com/assets/39355/14572697/cbe74908-0315-11e6-8def-561b35046ee6.gif)

**Comment by jmhobbs** [comment]
![party-parrot-dad-cropped](https://cloud.githubusercontent.com/assets/115059/14574375/e2dfef7e-0320-11e6-8859-fc840e80638a.gif)

Is it better in green or party colors?

**Comment by jmhobbs** [comment]
![parrot-dad-outlined](https://cloud.githubusercontent.com/assets/115059/14574487/90e92748-0321-11e6-9418-2babcc31195c.gif)

Outlined at least.

**Comment by zachleat** [comment]
If I had to pick one I'd say party colors but really I want both now

**Comment by jmhobbs** [comment]
IT IS DONE.

9b64ba2

**Comment by jaymcgavren** [comment]
OK, Google has failed me. I really need this explained.

**Comment by jmhobbs** [comment]
@jaymcgavren This circulated for a while named "parrot dad", so I added it as that.  No clue where it originated, and I don't think it's a Kakapo.

http://imgur.com/bO9k9B4

**Comment by vscabral** [comment]
You are correct that it is not a kakapo- it's a Parrotlet (feeding its chick). Here's the video source for the gif: https://www.facebook.com/forpus.org/videos/948507585195859/
