### ISSUE TITLE
Parrotwave appears out of sync :sadparrot:

### ISSUE THREAD

**Issue by lucymhdavies** [jmhobbs/cultofthepartyparrot.com#140]
![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave1.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave2.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave3.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave4.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave5.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave6.gif)![](https://github.com/jmhobbs/cultofthepartyparrot.com/raw/master/parrots/parrotwave7.gif)

**Comment by lucymhdavies** [comment]
Hmm. Maybe I'm wrong. Maybe it's just in Slack that it's weird, due to no guarantee that the images are loaded at the same time.

**Comment by captainEli** [comment]
@lucymhdavies Yes I've noticed that it gets out of sync in slack sometimes but it's never clear why and I haven't noticed a pattern. Weird.
