### ISSUE TITLE
Zombie Requested Parrot Please!

### ISSUE THREAD

**Issue by davidahopp** [jmhobbs/cultofthepartyparrot.com#154]

**Comment by uberchemist** [comment]
Guys... check this out and let me know what you think!
Parrot Zombie: ![zombie](https://user-images.githubusercontent.com/46827621/55163833-c019c700-5127-11e9-94a5-c2bf233fb3dd.gif)

**Comment by jmhobbs** [comment]
![I Am Uncomfortable](https://user-images.githubusercontent.com/115059/55174100-d4bb8680-514a-11e9-9171-919eb81ad048.jpg)

**Comment by davidahopp** [comment]
@uberchemist make the pull request!! looks great.

**Comment by uberchemist** [comment]
@davidahopp can I please get some assistance for that from @jmhobbs? pretty please?

**Comment by jmhobbs** [comment]
Will do!

**Comment by uberchemist** [comment]
Just noticed this never got added... perhaps too scary for the site? 🤔

**Comment by jmhobbs** [comment]
Nope!  I just lost track of it (surprise!)

**Comment by uberchemist** [comment]
Whoa! What year is it now? 🙃

**Comment by jmhobbs** [comment]
![Wow, ok. Harsh.](https://user-images.githubusercontent.com/115059/112690633-1d959b00-8e4a-11eb-84fc-73d07ff088bc.gif)

😜
