### ISSUE TITLE
Party Guests in the wrong location

### ISSUE THREAD

**Issue by danrichman** [jmhobbs/cultofthepartyparrot.com#174]
It looks as though the Party Guests were not invited to the same party that the hosts are throwing. The Guests appear to be way at the bottom of the page, where they are easily missed.

Wouldn't it make sense for the Party Guests to be directly below the Party Parrot hosts?

It's not really a party if the guests are excluded from all the fun and forced to party by themselves. ☹️

**Comment by jmhobbs** [comment]
Fair enough.  How about `Parrots > Download > Guests > Shirts...`

![screen shot 2017-11-07 at 1 38 54 pm](https://user-images.githubusercontent.com/115059/32513887-16757c16-c3c1-11e7-9f6d-b150c873c9cf.png)

**Comment by danrichman** [comment]
That seems reasonable to me, since we wouldn't want the download buttons to become confused. 👍

**Comment by jmhobbs** [comment]
I'll update it this evening.  Thanks!
