### ISSUE TITLE
Request: Troll Parrot

### ISSUE THREAD

**Issue by nuragic** [jmhobbs/cultofthepartyparrot.com#177]
Hi! 

I'm really missing the good ol :trollface: integration with our beloved `:parrot:` .... 

Whoever will implement this: I'll buy you a 🍺 !!! 😏 

Thanks! 😛  ❤️

**Comment by francoislg** [comment]
You can create your own using the Party Parrot as a Service endpoint:

![trollparrot](https://ppaas.herokuapp.com/partyparrot?overlay=https://assets-cdn.github.com/images/icons/emoji/trollface.png&overlayWidth=-20&overlayHeight=20&overlayOffsetX=18&overlayOffsetY=-10)

Here is the UI that you can use to create it: https://parrotify.github.io/

**Comment by cavpolloosigu** [comment]
@francoislg THAT IS PURE GOLD! D=

**Comment by nuragic** [comment]
@francoislg wow! haha thanks for the tip! great to know!
