### ISSUE TITLE
Party Parrot Web Component

### ISSUE THREAD

**Issue by nuragic** [jmhobbs/cultofthepartyparrot.com#181]
Hi! Just to make you know that I made a web component in order to easily include the parrot.

https://github.com/nuragic/party-parrot-web-component

Thanks!

**Comment by jmhobbs** [comment]
Right on! Submit a PR to add it to the [links section](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/master/templates/index.html#L147)?

**Comment by nuragic** [comment]
Oook sure will do it!
