### ISSUE TITLE
Christmas parrot

### ISSUE THREAD

**Issue by magnuspaaske** [jmhobbs/cultofthepartyparrot.com#184]
It's season, so I was thinking if there should be a Christmas parrot with a santa hat to set the mood :)

**Comment by cavpolloosigu** [comment]
There is a [christmas parrot](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/master/parrots/christmasparrot.gif) already =)

**Comment by magnuspaaske** [comment]
Sweet, thanks. Hadn't seen/imported it to slack yet so hadn't seen it :)
