### ISSUE TITLE
It's not just Slack... IS NOW ALSO DISCORD!

### ISSUE THREAD

**Issue by justalemon** [jmhobbs/cultofthepartyparrot.com#187]
[Discord](https://discordapp.com), a gamer chat and voice software recently added [Animated Emotes](https://twitter.com/discordapp/status/944011021512880128). In less than a few minutes I've found The Legendary Parrot on a lot of Discord Servers.

So perhaps, it's also "The only Discord animated emotes you'll ever need".

PD: In the Twitter link you will find an animation, just admire "shuflewumpus.gif".

**Comment by jmhobbs** [comment]
Right on!  I wonder if we can get an automated uploader for discord too.

**Comment by justalemon** [comment]
For that, you need a Bot that syncronize emotes using the Discord API. There's a lot of libraries for most programming languages.

**Comment by justalemon** [comment]
Also, this is a legit Discord Bug Report:
![image](https://user-images.githubusercontent.com/11861253/34311096-33390e84-e73a-11e7-854c-70e2fdd4fb4a.png)

**Comment by Kizzaris** [comment]
There's a maximum of 50 animated emojis per server, you would need 3 servers to contain all the parrots.
I'll try to do something in Eris and see what happens.

**Comment by Kizzaris** [comment]
Alright, I finished the bot that added some basic Party Parrot emotes to the server it's run on.
You can check it out in action over at https://discord.gg/BG3AUfh or see the source at https://github.com/Kizzaris/partydiscord

Here is a gif of it doing it's thing:
![the bot doing it's thing](https://i.imgur.com/Jeeoe5C.gif)

**Comment by jmhobbs** [comment]
That's pretty awesome.  I'll add some links to the website.
