### ISSUE TITLE
Coffee Parrot and some others are somehow "executable?"

### ISSUE THREAD

**Issue by Clpsplug** [jmhobbs/cultofthepartyparrot.com#189]
I know this is so nitpicky, but I was wondering why some of the parrots on [cultofthepartyparrot.com](cultofthepartyparrot.com) came out of the zip file having executable permissions (`755` or `rwxr-xr-x`.)  
Current master branch have this issue (notice the "Executable file" on the left of the file size:) https://github.com/jmhobbs/cultofthepartyparrot.com/commit/6e806a7c5c096b68a3e77722d2613d2686804ed5#diff-47bc58a58f938484aaa84c663487f038  
(the link to file is pinned down by commit to avoid losing track of the status)

I first found the executable permission on the Coffee Parrot, so I thought this was some kind of reference to CoffeeScript, but apparently, the following HD parrots whose reference I can't think of are also "executable."

* HD Blunt Parrot and
* HD Conga Parrot

Of course, none of those 'run.' Do these guys intentionally have their permissions? If not I'll consider creating PR which will remove them.

**Comment by jmhobbs** [comment]
Nope, that's not intentional at all. Feel free to PR on that or I can get to it later. Thanks!

**Comment by jmhobbs** [comment]
Closed by #190
