### ISSUE TITLE
Aussie Conga Parrots

### ISSUE THREAD

**Issue by lucymhdavies** [jmhobbs/cultofthepartyparrot.com#19]
We've had this for a while
![conga](http://cultofthepartyparrot.com/parrots/congaparrot.gif)![conga](http://cultofthepartyparrot.com/parrots/congaparrot.gif)![conga](http://cultofthepartyparrot.com/parrots/congaparrot.gif)![conga](http://cultofthepartyparrot.com/parrots/congaparrot.gif)![conga](http://cultofthepartyparrot.com/parrots/congaparrot.gif)

And we now have this...
![reverseconga](http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif)![reverseconga](http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif)![reverseconga](http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif)![reverseconga](http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif)![reverseconga](http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif)

What about an Aussie version of both?

**Comment by samlindsaylevine** [comment]
I attempted to meet this need as pull request #28 .

**Comment by jmhobbs** [comment]
Closed by 6dd5273, thanks @samlindsaylevine!
