### ISSUE TITLE
Request: Gopher Guest Gif

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#192]
Because Go is a great language!

**Comment by FedeCaceres** [comment]
+1 #

**Comment by kiwivogel** [comment]
I think this can be closed now :D 
![partygopher](https://user-images.githubusercontent.com/3089920/42684707-34ad885c-8691-11e8-9d32-06a9e5d881ee.gif)

**Comment by jmhobbs** [comment]
Excellent point!  Closed by #236
