### ISSUE TITLE
Automatic slack upload fails on Google sign in

### ISSUE THREAD

**Issue by Darth-Arminius** [jmhobbs/cultofthepartyparrot.com#199]
The current upload_parrots.py script only works for default Slack sign in. Some slack teams (like the ones I am part of) use Google sign in.

Fortunately, the script only requires a minor change to get it working with Google sign in as it is mainly just element changes.

Replace:
```python
        username_field = self.browser.find_element(value="email")
        password_field = self.browser.find_element(value='password')

        username_field.send_keys(username)
        password_field.send_keys(password)
        username_field.submit()
```

With:
```python
        signin_button = self.browser.find_element_by_partial_link_text("Sign in with Google")
        signin_button.click()
        time.sleep(5)

        username_field = self.browser.find_element_by_tag_name("input")
        username_field.send_keys(username)
        email_next = self.browser.find_element_by_id("identifierNext")
        email_next.click()
        time.sleep(5)

        password_field = self.browser.find_element_by_name("password")
        password_field.send_keys(password)
        password_next = self.browser.find_element_by_id("passwordNext")
        password_next.click()
        time.sleep(5)
```

Or something along those lines.

I don't know if the sleep is completely necessary but I was running into element not found issues without it as it was trying to access the next page's elements before they loaded.

This could be added as a choice to the user based on whether they sign in with Google or not and accessed by another arg but ultimately its down to what people think and whether its really needed.

All in all, managed to upload all the Parrots to our team using this so its out there if anyone else needs to use it.

**Comment by Darth-Arminius** [comment]
I wrote up something quick that does the job but I am quite the Python noob so its nothing special and I'm sure someone else can come up with something better. Could serve as a reference point at least:

[Commit link](https://github.com/Darth-Arminius/cultofthepartyparrot.com/commit/aafe30e2b14e2fef306c49c1ed3b2c22c7836a40)
[File link](https://github.com/Darth-Arminius/cultofthepartyparrot.com/blob/master/upload_parrots.py)

**Comment by Darth-Arminius** [comment]
I updated the above script and made it nicer. I created a pull request you can take a look at go from there.
[Pull Request](https://github.com/jmhobbs/cultofthepartyparrot.com/pull/200)

**Comment by santiycr** [comment]
I can help out with this

**Comment by Darth-Arminius** [comment]
Resolved in [this ](https://github.com/jmhobbs/cultofthepartyparrot.com/pull/200) pull request.
