### ISSUE TITLE
Party parrot is a New Zealand bird, so the upside down version is a Northern Hemisphere parrot

### ISSUE THREAD

**Issue by mermop** [jmhobbs/cultofthepartyparrot.com#2]
Sirocco is a New Zealand kakapo who is known for being more attracted to humans than other kakapo. The party parrot gif was derived from this video:
https://www.youtube.com/watch?v=6A7uFSbRJ5w
![sirocco](https://cloud.githubusercontent.com/assets/1615322/12770167/0f76db3c-ca83-11e5-8eec-d3db0397d068.gif)

As he is from New Zealand, the upside down version should really be :american_parrot:.

I also encourage you to put a link to donate to the recovery of this endangered, hard partying bird
http://kakaporecovery.org.nz/sirocco/

**Comment by glsignal** [comment]
:+1:

**Comment by moskyb** [comment]
👍

**Comment by MichaelDowse** [comment]
:+1:

**Comment by OBaddeley** [comment]
:+1:

**Comment by thejduce** [comment]
👍🏼

**Comment by jmhobbs** [comment]
AMAZING!  Thanks!

**Comment by jmhobbs** [comment]
@mermop Added the info and links to donate.  Anyone who has better wording options, please chime in.

Closing the `:american_parrot:` as won't fix because I'm a stubborn american ;)

**Comment by heisenburger** [comment]
:+1:

**Comment by mermop** [comment]
:raised_hands:

**Comment by xavizalote** [comment]
:+1:

**Comment by stewartknapman** [comment]
The Kakapo is endemic to New Zealand so shouldn't `:aussie_parrot:` at least be changed to `:nz_parrot:`?

**Comment by grant** [comment]
Another link: https://www.youtube.com/watch?v=9T1vfsHYiKY
