### ISSUE TITLE
Request: Portal Parrot

### ISSUE THREAD

**Issue by juniormucciolo** [jmhobbs/cultofthepartyparrot.com#202]
Hello,

Please add portal parrot or/and fast portal parrot

1) https://emoji.slack-edge.com/T43HKDBAR/portalparrot/c4746451aa4cd4af.gif
2) https://emoji.slack-edge.com/T43HKDBAR/fastportalparrot/a474859015ec501b.gif

ty! :)

**Comment by jmhobbs** [comment]
That's great!  Will do.

**Comment by mateusc-ciandt** [comment]
:+1:

**Comment by bberton-ciandt** [comment]
:+1:

**Comment by mconilho-ciandt** [comment]
:+1:

**Comment by danilop-ciandt** [comment]
:+1:

**Comment by marcosouza-ciandt** [comment]
:+1:

**Comment by guilhermeb-ciandt** [comment]
:+1:

**Comment by lucasgf-ciandt** [comment]
:+1:

**Comment by cavpolloosigu** [comment]
+1

**Comment by chgasparoto** [comment]
![1f44d](https://user-images.githubusercontent.com/2037349/36500429-0762d786-1723-11e8-97e4-b384750276ca.png)

**Comment by chgasparoto** [comment]
:+1:

**Comment by jmhobbs** [comment]
I'm beginning to think this might be in use at CI&T....

**Comment by ffedel-ciandt** [comment]
Ora, ora, temos um Xeroque Rolmes aqui
