### ISSUE TITLE
Update deal with it parrot.

### ISSUE THREAD

**Issue by dnguyenchevy** [jmhobbs/cultofthepartyparrot.com#21]
I feel like the deal with it parrot is not sufficient until we get 1 full rotation then the glasses coming down on it.

I'm not great with gif editing, could we get this?

**Comment by Nino55N** [comment]
+1

**Comment by jmhobbs** [comment]
Paging @tysondreeder

**Comment by tysondreeder** [comment]
On it

**Comment by jmhobbs** [comment]
![Yaaaasssss](http://dropit.velvetcache.org.s3.amazonaws.com/jmhobbs/MTU4lOuLiQ/happy.gif)

**Comment by dnguyenchevy** [comment]
Reopening because I am not satisfied with the outcome. I was expecting the parrot to do a full head rotation and then the glasses falling onto the parrot.

**Comment by tysondreeder** [comment]
updated!
![dealwithitparrot](https://cloud.githubusercontent.com/assets/5118106/15733060/00cb1d64-2848-11e6-8148-7abf21775d43.gif)

**Comment by Nino55N** [comment]
Love it! 🌝

**Comment by dnguyenchevy** [comment]
Yessssssssssssss!

**Comment by oliviag** [comment]
Before I saw this, I had independently made these for my company's slack... Slightly different approach. Love this simpler one!!

![dealwithit-drop-parrot-2](https://cloud.githubusercontent.com/assets/1513332/15783671/0fae8c18-297d-11e6-9ff5-5322cfc4ff75.gif)

**Comment by jmhobbs** [comment]
Oh man, I like them both 😕

**Comment by jmhobbs** [comment]
Maybe we need an "alternates" zip...

**Comment by daveyarwood** [comment]
@oliviag 's is perfect, IMHO!
