### ISSUE TITLE
Parrot Layout

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#22]
This is getting out of hand.  We need a new layout.

<img width="371" alt="screen shot 2016-05-17 at 4 33 28 pm" src="https://cloud.githubusercontent.com/assets/115059/15340065/29eaf1da-1c4d-11e6-9730-1e611bd2c0bc.png">

**Comment by dnguyenchevy** [comment]
How do we feel about grid layout? I'll try to get something mock up.

**Comment by jmhobbs** [comment]
Sure!  I played with two columns, but it looked unbalanced.

Maybe putting the Parrot title under the gif would help.

**Comment by dnguyenchevy** [comment]
![capture](https://cloud.githubusercontent.com/assets/5448499/15380695/44991ccc-1d3e-11e6-9a47-1ccad91192f3.JPG)

Like so? Before I continue on with the other million parrots.

**Comment by Nino55N** [comment]
+1 🌝

**Comment by jmhobbs** [comment]
Nice!  I like it.

**Comment by jmhobbs** [comment]
Need to take into consideration #27 with this.

**Comment by jmhobbs** [comment]
Rough version was added in 3d726b4f5d3fe9fba368daa1a83e40e46f6b670b, closing this one for now.
