### ISSUE TITLE
Question: Are PNG party parrots acceptable?

### ISSUE THREAD

**Issue by PhaserArray** [jmhobbs/cultofthepartyparrot.com#224]
A friend of mine (`@Pixel#2101` on Discord and [a_pixel on Steam](https://steamcommunity.com/id/a_pixel/)) created [this static party parrot emoji](https://i.imgur.com/r4cY1tb.png) for Discord users that do not have a Discord Nitro subscription (required for GIF emojis).   
May I send a PR request with it included and is the method for adding it the same as adding a GIF?

EDIT: Don't know why I didn't think of it before, I can also convert it to a non-animated GIF and add that if static parrots are ok.

**Comment by melinerunen** [comment]
@PhaserArray  is this related to #233 ? If so I'll close this and use the other one.

**Comment by PhaserArray** [comment]
It is, feel free to close this.

**Comment by melinerunen** [comment]
relates to #233
