### ISSUE TITLE
This is not the right place for this

### ISSUE THREAD

**Issue by borisrev** [jmhobbs/cultofthepartyparrot.com#234]
but here it is anyway.

www.gtfoparrot.com

**Comment by jmhobbs** [comment]
I have no idea what to do with this but it's amazing.

**Comment by borisrev** [comment]
Just spread the Glorious Word of the Party Parrot, my brother

**Comment by onebree** [comment]
Did you create this glorious site, @borisrev ? I love how the parrot changes, and explodes with more parrots on each click

**Comment by jmhobbs** [comment]
WHAT.  ITS INTERACTIVE?!  I totally missed that when I checked it out.  That's amazing.
