### ISSUE TITLE
Alternative versions of parrots

### ISSUE THREAD

**Issue by JacopoGobbi** [jmhobbs/cultofthepartyparrot.com#25]
Congaparrot with glasses 
![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)![congapartyparrot](https://cloud.githubusercontent.com/assets/11658632/15711185/f9e09058-2804-11e6-9eef-48c43671e3b9.gif)

**Comment by JacopoGobbi** [comment]
Parakeet:
![parakeet](https://cloud.githubusercontent.com/assets/11658632/16445417/83c02afa-3dda-11e6-805f-8b275212a905.gif)
Party parakeet:
![partyparakeet](https://cloud.githubusercontent.com/assets/11658632/16445426/8d4fe628-3dda-11e6-999e-bab420ee2389.gif)
(soon I'll make a PR)

**Comment by natelowry** [comment]
Sassy parrot:
![Sassy Parrot](http://im.ezgif.com/tmp/ezgif-3945332551.gif)

**Comment by Nino55N** [comment]
+1 a million

**Comment by Nino55N** [comment]
Actually we need to add the sassy parrot plz

**Comment by natelowry** [comment]
Weekend project! :dancers: 

Will PR
