### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by WillMoreland** [jmhobbs/cultofthepartyparrot.com#256]
Hey, I'd love to link to these parrots in places like my company's Github but can't because the website doesn't use HTTPS. Are we able to use [Let's Encrypt](https://letsencrypt.org/) or something to enable HTTPS for the site?

**Comment by jmhobbs** [comment]
Done!  Thought I'd already done that in the past.

https://www.ssllabs.com/ssltest/analyze.html?d=cultofthepartyparrot.com&latest

Thanks!

**Comment by WillMoreland** [comment]
@jmhobbs thanks for sorting that so quickly! I noticed that it still defaults to http, would you want to set it to default?

**Comment by jmhobbs** [comment]
Also a good idea, and also done!  Thanks!

**Comment by WillMoreland** [comment]
Thanks dude, you rock! ![](https://cultofthepartyparrot.com/parrots/shipitparrot.gif)
