### ISSUE TITLE
How can I get access rights?

### ISSUE THREAD

**Issue by Jegama** [jmhobbs/cultofthepartyparrot.com#257]
I did a parrot but don't have access rights to upload a new branch, 

![calvinist_parrot](https://user-images.githubusercontent.com/12228031/44807967-89c79980-ab90-11e8-9fd4-1c62a57c6d0a.gif)

If we have a papal parrot, we need a reformed parrot hehe.

**Comment by cavpolloosigu** [comment]
You have to fork the repository, make your changes, and then make a pull request :slightly_smiling_face: 
[This may help you](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by Jegama** [comment]
Great, thanks!
