### ISSUE TITLE
How about a pepe parrot?

### ISSUE THREAD

**Issue by Aniket-Pradhan** [jmhobbs/cultofthepartyparrot.com#276]
Not Pepe the footballer, but [Pepe the frog](https://www.thewrap.com/wp-content/uploads/2016/09/1200.jpg)!

**Comment by jmhobbs** [comment]
Hello!

We’ve had discussion around Pepe in the past (issues #223 and #32) and have decided that Pepe is not something we will add to the site.

Feel free to submit other ideas or add your own parrots if you make any.

Thanks, and party on!

**Comment by Aniket-Pradhan** [comment]
Oh, poor Pepe.

Anyways... Party On!
