### ISSUE TITLE
New HD parrots to add

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#297]
Still getting used to the way of the Github, and somewhat lazy, so posting links here to my latest creations:
Stable Parrot: https://imgur.com/y435lRG
Canadian Parrot: https://imgur.com/mpAgy8n
Mexican Parrot: https://imgur.com/kHUEHtA
Serbian Parrot: https://imgur.com/zkfpVPW
Under Construction Parrot: https://imgur.com/vzzVLbw
Parrot Twins: https://imgur.com/4u8f667
Thanks ahead of time for anyone's help adding these. Still working on more! Currently trying to get a football parrot created in time for the Super Bowl.
![canada](https://user-images.githubusercontent.com/46827621/51703632-b65ed080-1fcb-11e9-8ff0-39d29986bd5c.gif)
![construction](https://user-images.githubusercontent.com/46827621/51703633-b65ed080-1fcb-11e9-8c36-3f1b9d3eb650.gif)
![mexico](https://user-images.githubusercontent.com/46827621/51703634-b65ed080-1fcb-11e9-8932-bfe5390a687c.gif)
![serbia](https://user-images.githubusercontent.com/46827621/51703635-b65ed080-1fcb-11e9-9f3a-ddccee9da2ef.gif)
![stable](https://user-images.githubusercontent.com/46827621/51703636-b6f76700-1fcb-11e9-81f4-e782cc78ba36.gif)
![twins](https://user-images.githubusercontent.com/46827621/51703735-faea6c00-1fcb-11e9-91d3-ca1ff28d73b3.gif)

**Comment by jmhobbs** [comment]
Yes!  Maybe we should split the flag parrots into their own group, like guests.

Thanks, I'll get these in soon.
