### ISSUE TITLE
Contributing more new HD parrots

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#300]
Files (and links) to the follow new party parrots below!
Red Hat Parrot: https://imgur.com/FfKvZbw
Football Parrot: https://imgur.com/H2lJxwM
NICK CAGE Parrot: https://imgur.com/Dcb3wdp
China Parrot: https://imgur.com/VNkVdb8
Taiwan Parrot: https://imgur.com/sORoS6O
South Korea Parrot: https://imgur.com/JTIm5GA
![china](https://user-images.githubusercontent.com/46827621/51778006-8b9c7700-20b4-11e9-98af-c3aa4419bb6f.gif)
![football](https://user-images.githubusercontent.com/46827621/51778007-8c350d80-20b4-11e9-9971-682f010ad1a6.gif)
![nickcage](https://user-images.githubusercontent.com/46827621/51778008-8c350d80-20b4-11e9-812d-8f1e94c9f9e9.gif)
![redhat](https://user-images.githubusercontent.com/46827621/51778010-8c350d80-20b4-11e9-88bd-97165163a3d8.gif)
![southkorea](https://user-images.githubusercontent.com/46827621/51778011-8c350d80-20b4-11e9-8506-352f14fb7771.gif)
![taiwan](https://user-images.githubusercontent.com/46827621/51778012-8c350d80-20b4-11e9-8709-b1ea49ed2a03.gif)

**Comment by jmhobbs** [comment]
Thank you!
