### ISSUE TITLE
Add Request: Loads more of the HD flag parrots plus a few others

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#308]
Here you go guys! Let me know what you think!

[Bored Parrot](https://imgur.com/1bV8Ede): ![bored](https://user-images.githubusercontent.com/46827621/52422285-a1de0600-2aaa-11e9-9623-ec3ff3846af8.gif)
[Spinning Parrot](https://imgur.com/iWdHZLX): ![spin](https://user-images.githubusercontent.com/46827621/52422299-a5718d00-2aaa-11e9-8c5b-71eb05f8b79e.gif)
[Sleeping Parrot](https://imgur.com/5x8bzX3): ![sleep](https://user-images.githubusercontent.com/46827621/52422303-a73b5080-2aaa-11e9-9752-16b928f5df51.gif)
[Parrot Not Found](https://imgur.com/qQXDnxJ): ![missing](https://user-images.githubusercontent.com/46827621/52422307-a9051400-2aaa-11e9-8b32-a26ea83337c1.gif)
[Red Envelope Parrot](https://imgur.com/jxQ63D9): ![redenvelope](https://user-images.githubusercontent.com/46827621/52422331-b6ba9980-2aaa-11e9-828e-954d2a64733a.gif) (for the Lunar New Year)

### **And a ton of Flag Parrots!**
[Denmark](https://imgur.com/wGM5NrJ): ![denmark](https://user-images.githubusercontent.com/46827621/52422669-5f68f900-2aab-11e9-93c9-e2f25ab2740e.gif)
[Finland](https://imgur.com/R4BnVYT): ![finland](https://user-images.githubusercontent.com/46827621/52422673-61cb5300-2aab-11e9-8eb6-6752bc578172.gif)
[Norway](https://imgur.com/us9ka2b): ![norway](https://user-images.githubusercontent.com/46827621/52422677-63951680-2aab-11e9-81b8-cc2a07583c8d.gif)
[Iceland](https://imgur.com/6EAFso6): ![iceland](https://user-images.githubusercontent.com/46827621/52422679-655eda00-2aab-11e9-85d2-be48fa895659.gif)
[Poland](https://imgur.com/28uknXE): ![poland](https://user-images.githubusercontent.com/46827621/52422683-67c13400-2aab-11e9-8b57-ab55a174e659.gif)
[Switzerland](https://imgur.com/TkIdvVY): ![switzerland](https://user-images.githubusercontent.com/46827621/52422688-698af780-2aab-11e9-8145-c0b200135a4b.gif)
[Vietnam](https://imgur.com/LKpY7pq): ![vietnam](https://user-images.githubusercontent.com/46827621/52422693-6b54bb00-2aab-11e9-8c4d-00ce80c927bd.gif)
[Hong Kong](https://imgur.com/fsuLiJd): ![hongkong](https://user-images.githubusercontent.com/46827621/52422696-6db71500-2aab-11e9-834c-5bfe8881cb64.gif)
[Macau](https://imgur.com/8vqZ7al): ![macau](https://user-images.githubusercontent.com/46827621/52422698-6f80d880-2aab-11e9-8657-b27ea8107f45.gif)
[Italy](https://imgur.com/bi2SQ79): ![italy](https://user-images.githubusercontent.com/46827621/52422703-714a9c00-2aab-11e9-8390-4e01e0862ee6.gif)
[Russia](https://imgur.com/CKsiXuW): ![russia](https://user-images.githubusercontent.com/46827621/52422708-727bc900-2aab-11e9-9016-1b5951decd01.gif)
[Greece](https://imgur.com/vDp95oe): ![greece](https://user-images.githubusercontent.com/46827621/52422713-74de2300-2aab-11e9-8b77-022eb1178e15.gif)
[Venezuela](https://imgur.com/z4fILFy): ![venezuela](https://user-images.githubusercontent.com/46827621/52422715-76a7e680-2aab-11e9-819a-739d83df7536.gif)
[Austria](https://imgur.com/VQWp3AH): ![austria](https://user-images.githubusercontent.com/46827621/52422720-7871aa00-2aab-11e9-87c9-ddbbcae4399f.gif)
[Ukraine](https://imgur.com/I9Q2dul): ![ukraine](https://user-images.githubusercontent.com/46827621/52422724-7b6c9a80-2aab-11e9-8c07-b68a15255c2d.gif)
[Hungary](https://imgur.com/3T4CM8W): ![hungary](https://user-images.githubusercontent.com/46827621/52422726-7d365e00-2aab-11e9-939d-65bfaf631b70.gif)
[Slovakia](https://imgur.com/OMpF63A): ![slovakia](https://user-images.githubusercontent.com/46827621/52422728-7f002180-2aab-11e9-8f78-b0ff1293d234.gif)
[Czech Republic](https://imgur.com/AKq2TBH): ![czechrepublic](https://user-images.githubusercontent.com/46827621/52422729-80c9e500-2aab-11e9-8786-18ca4eac2ab3.gif)
[Belgium](https://imgur.com/h5SgZ5L): ![belgium](https://user-images.githubusercontent.com/46827621/52422732-81fb1200-2aab-11e9-9e80-9da91f14d73a.gif)
[North Korea](https://imgur.com/fGDfnna): ![northkorea](https://user-images.githubusercontent.com/46827621/52422736-83c4d580-2aab-11e9-8e1d-372f0a72512b.gif)
[Thailand](https://imgur.com/6NJdv8T): ![thailand](https://user-images.githubusercontent.com/46827621/52422739-858e9900-2aab-11e9-853f-18611dfd525a.gif)
[Cambodia](https://imgur.com/ohf7Hh0): ![cambodia](https://user-images.githubusercontent.com/46827621/52422741-87585c80-2aab-11e9-89e2-c061e017ee0a.gif)
[Laos](https://imgur.com/JvzwiyS): ![laos](https://user-images.githubusercontent.com/46827621/52422746-89bab680-2aab-11e9-9ea9-d9d20ddb8d1a.gif)
[Mongolia](https://imgur.com/lsB6rG0): ![mongolia](https://user-images.githubusercontent.com/46827621/52422748-8b847a00-2aab-11e9-92b2-e8219ee9f04a.gif)

**Comment by jmhobbs** [comment]
OMG I love `Parrot Not Found`.  You're a parrot making wonder @uberchemist!  I'll load these up.
