### ISSUE TITLE
Another load of HD flag parrots - plus Groucho!

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#312]
Cranking these out in my free time...

But here's one special guy:

[Groucho Parrot](https://imgur.com/PHCrnjM): ![groucho](https://user-images.githubusercontent.com/46827621/52754481-85146780-2faf-11e9-8e94-087d8d36dffc.gif)
Hoping to complete Chico and Harpo in the near future!

### **On with the flag parrots!**

[Checkered Flag](https://imgur.com/4zGIVcw): ![checkered](https://user-images.githubusercontent.com/46827621/52754765-8f833100-2fb0-11e9-933d-55e37cea3898.gif)
[Romania](https://imgur.com/xydVhZ9):![romania](https://user-images.githubusercontent.com/46827621/52754777-9742d580-2fb0-11e9-8da1-120793df06da.gif)
[Luxembourg](https://imgur.com/T7sE5br): ![luxembourg](https://user-images.githubusercontent.com/46827621/52754782-99a52f80-2fb0-11e9-8d68-042f0c5ce146.gif)
[Monaco](https://imgur.com/hETjUVM): ![monaco](https://user-images.githubusercontent.com/46827621/52754790-9ca02000-2fb0-11e9-9533-556cb3c2382c.gif)
[Morocco](https://imgur.com/uK1AasU): ![morocco](https://user-images.githubusercontent.com/46827621/52754796-a164d400-2fb0-11e9-893d-e30837c50306.gif)
[Algeria](https://imgur.com/zhOzfbW): ![algeria](https://user-images.githubusercontent.com/46827621/52754893-facd0300-2fb0-11e9-8151-205df8503cf6.gif)
[Libya](https://imgur.com/Y4qe8b5): ![libya](https://user-images.githubusercontent.com/46827621/52754895-fc96c680-2fb0-11e9-8c01-4ec087f14456.gif)
[Egypt](https://imgur.com/pOVRd1K): ![egypt](https://user-images.githubusercontent.com/46827621/52754898-fef92080-2fb0-11e9-94ff-b5cf4dc698d6.gif)
[Brazil](https://imgur.com/snZ1FMP): ![brazil](https://user-images.githubusercontent.com/46827621/52754900-00c2e400-2fb1-11e9-8c9b-3fcc2edd6b16.gif)
[Iraq](https://imgur.com/xrA1Ihm): ![iraq](https://user-images.githubusercontent.com/46827621/52754906-03bdd480-2fb1-11e9-9feb-d2dbc264d3d4.gif)
[Iran](https://imgur.com/ewp5Teq): ![iran](https://user-images.githubusercontent.com/46827621/52754909-05879800-2fb1-11e9-8564-05b28162aa2c.gif)
[Israel](https://imgur.com/HCqx5gr): ![israel](https://user-images.githubusercontent.com/46827621/52754915-07e9f200-2fb1-11e9-9ca5-3c0ef0adebd8.gif)
[Palestine](https://imgur.com/dn8buys): ![palestine](https://user-images.githubusercontent.com/46827621/52754916-09b3b580-2fb1-11e9-8f19-0a944ba255c4.gif)
[Jordan](https://imgur.com/7tYAQbu): ![jordan](https://user-images.githubusercontent.com/46827621/52754918-0b7d7900-2fb1-11e9-90c8-8e2c55febfda.gif)
[Lebanon](https://imgur.com/JF2G4DD): ![lebanon](https://user-images.githubusercontent.com/46827621/52754920-0d473c80-2fb1-11e9-8067-96537a737e6b.gif)
[Syria](https://imgur.com/0Whtqnu): ![syria](https://user-images.githubusercontent.com/46827621/52754926-0f110000-2fb1-11e9-8db8-83b433a38809.gif)
[Saudi Arabia](https://imgur.com/fcx1nSv): ![saudiarabia](https://user-images.githubusercontent.com/46827621/52754932-120bf080-2fb1-11e9-9537-a5a8f2fdad51.gif)
[Greenland](https://imgur.com/QCOAENK): ![greenland](https://user-images.githubusercontent.com/46827621/52754934-13d5b400-2fb1-11e9-97cf-0b3e992226b9.gif)
[Cuba](https://imgur.com/mSK2071): ![cuba](https://user-images.githubusercontent.com/46827621/52754936-159f7780-2fb1-11e9-92e5-0af09d0a946d.gif)
[Guatemala](https://imgur.com/NBfJdJm): ![guatemala](https://user-images.githubusercontent.com/46827621/52754941-17693b00-2fb1-11e9-87b2-d32f70a3c789.gif)
[Belize](https://imgur.com/ZYOXpm1): ![belize](https://user-images.githubusercontent.com/46827621/52754946-1932fe80-2fb1-11e9-9529-29e2b6d44850.gif)
[El Salvador](https://imgur.com/dmrfJjl): ![elsalvador](https://user-images.githubusercontent.com/46827621/52754948-1b955880-2fb1-11e9-836b-9c3aa994f955.gif)
[Honduras](https://imgur.com/hyscLaM): ![honduras](https://user-images.githubusercontent.com/46827621/52754952-1d5f1c00-2fb1-11e9-895d-a5a8072057fc.gif)
[Nicaragua](https://imgur.com/ToJcLW3): ![nicaragua](https://user-images.githubusercontent.com/46827621/52754956-1f28df80-2fb1-11e9-9825-c6dfd7a3bc6b.gif)
[Costa Rica](https://imgur.com/kk6BY60): ![costarica](https://user-images.githubusercontent.com/46827621/52754958-218b3980-2fb1-11e9-9cd3-ebd1032dad36.gif)
[Panama](https://imgur.com/aqhUxRL): ![panama](https://user-images.githubusercontent.com/46827621/52754961-24862a00-2fb1-11e9-8dfb-d35c8b43d540.gif)
[Jamaica](https://imgur.com/6sPEuSh): ![jamaica](https://user-images.githubusercontent.com/46827621/52754966-264fed80-2fb1-11e9-9c3a-3d2acf4e575c.gif)
[Haiti](https://imgur.com/SvIzSJQ): ![haiti](https://user-images.githubusercontent.com/46827621/52754968-2819b100-2fb1-11e9-9651-115826762020.gif)
[Dominican Republic](https://imgur.com/sZhRpNs): ![dominicanrepublic](https://user-images.githubusercontent.com/46827621/52754971-2a7c0b00-2fb1-11e9-92e9-0a8f1fd6d37c.gif)
[Puerto Rico](https://imgur.com/HgJzxEN): ![puertorico](https://user-images.githubusercontent.com/46827621/52754972-2cde6500-2fb1-11e9-988e-ca308a1e159e.gif)

Some remakes:

[United Kingdom](https://imgur.com/JZsbiRH): ![unitedkingdom](https://user-images.githubusercontent.com/46827621/52754678-403d0080-2fb0-11e9-9825-79d2b0de5323.gif) (I made it from scratch like the others, but this is very similar to the pre-existing UK parrot)
[LGBT Pride](https://imgur.com/UxYdVu2): ![lgbtpride](https://user-images.githubusercontent.com/46827621/52754674-3ca97980-2fb0-11e9-826c-d19573ae1c98.gif) (flag pattern moves along with parrot)
[Transgender Pride](https://imgur.com/ILcLog9): ![transgenderpride](https://user-images.githubusercontent.com/46827621/52754669-3a471f80-2fb0-11e9-9f59-c82c18c62a22.gif) (ditto)

**Comment by cavpollo** [comment]
Groucho!!! Yay
Also, Guatemala Parrot is looking cooler than the rest :+1: (Not that I'm biased by my home country)

**Comment by uberchemist** [comment]
Okay, one more to add. Here's [Chico](https://imgur.com/GerBDqk)!
![chico](https://user-images.githubusercontent.com/46827621/52818008-61f2c200-305a-11e9-93d7-83aae22d41d2.gif)

**Comment by jmhobbs** [comment]
Nice!  I'm going to swap in your pride flag parrots, I like how the flag moves with it.

**Comment by jmhobbs** [comment]
Piled into #314 if anyone wants to spell check me over there.
