### ISSUE TITLE
Build Fails with "Task never defined: build"

### ISSUE THREAD

**Issue by tgockel** [jmhobbs/cultofthepartyparrot.com#317]
Following the instructions from `README.md` (First, you need to clone this repo and run the build script with npm run build or yarn build) fails on the first step with output that looks like this:

```
$> npm run build

> cultofthepartyparrot.com@1.1.0 build /home/travis/projects/external/cultofthepartyparrot
> gulp build

[16:36:56] Using gulpfile ~/projects/external/cultofthepartyparrot/gulpfile.js
[16:36:56] Task never defined: build
[16:36:56] To list available tasks, try running: gulp --tasks
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cultofthepartyparrot.com@1.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cultofthepartyparrot.com@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-02-18T23_36_56_141Z-debug.log
```

It is complaining about missing a `build` task, which I assume is due to there being nothing that looks like `gulp.task('build', function () { ... })` in `gulpfile.js`. I tried to follow the `gulp --tasks` suggestion in the output, but that can't possibly work for me, since `gulp` is not installed on my system. Normally I would install this via a package manager, but none of these things are in my available packages and installing them through NPM doesn't appear to do anything remotely useful. I know very little about NPM and Gulp, but these tools seem incredibly unhelpful.

**Comment by tgockel** [comment]
After installing everything in `make`, I can run `./make build`, but that does not work either:

```
$> ./make build
==[ build ]==
==[ test ]==
[16:58:26] Using gulpfile ~/projects/external/cultofthepartyparrot/gulpfile.js
/usr/lib/nodejs/gulp/bin/gulp.js:132
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by jmhobbs** [comment]
I wrote the makefile because I am not a JS dev and was fed up trying to get a full build working through Gulp, but JS is where all the CSS minification tools are these days so it's got to hang around somewhat.

I'll try to sort that out and update the docs.

**Comment by tgockel** [comment]
I'm not a JS dev either, so I'm sorry I can't be more helpful here.

**Comment by francoislg** [comment]
```
[16:36:56] Using gulpfile ~/projects/external/cultofthepartyparrot/gulpfile.js
[16:36:56] Task never defined: build
[16:36:56] To list available tasks, try running: gulp --tasks
```
means that `build` is not a valid gulp task.

It has indeed been removed in this commit:

https://github.com/jmhobbs/cultofthepartyparrot.com/commit/77573eae5cb9ecc103239b92712b7f3e069427f1#diff-b9e12334e9eafd8341a6107dd98510c9

I think the documentation was simply not updated following this change :)

**Comment by jmhobbs** [comment]
Created a PR to address this if you want to take a look.
