### ISSUE TITLE
Viking Parrot

### ISSUE THREAD

**Issue by ricardofiorani** [jmhobbs/cultofthepartyparrot.com#319]
Is it possible to add an Viking parrot ? It can be just a parrot with a viking helmet.

**Comment by jmhobbs** [comment]
I'll add the help wanted label, hopefully someone will make one soon!

**Comment by uberchemist** [comment]
Ask and ye shall receive!

[Viking Parrot](https://imgur.com/cO2O1KS): ![viking](https://user-images.githubusercontent.com/46827621/53676004-cebcad80-3c51-11e9-80ef-80e0ef1e5447.gif)

**Comment by jmhobbs** [comment]
@uberchemist to the rescue!  I'll get this added to the site, thanks!

**Comment by ricardofiorani** [comment]
Thank you guys !!!
