### ISSUE TITLE
More parrots for submission!

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#320]
Viking Parrot: ![viking](https://user-images.githubusercontent.com/46827621/53676337-9a4af080-3c55-11e9-8b80-b4716a5db7b3.gif)(Previously posted in another issue)
**Harpo Marx Parrot**: ![harpo](https://user-images.githubusercontent.com/46827621/53676338-9a4af080-3c55-11e9-9c53-b460b16c86ee.gif)(Finishes out the trio!)

### **...and MOAR flag parrots!**

Guyana: ![guyana](https://user-images.githubusercontent.com/46827621/53676348-e4cc6d00-3c55-11e9-8182-dac34ba1e8a2.gif)
Ecuador: ![ecuador](https://user-images.githubusercontent.com/46827621/53676349-e4cc6d00-3c55-11e9-947d-f1f74b3b1a44.gif)
Peru: ![peru](https://user-images.githubusercontent.com/46827621/53676350-e4cc6d00-3c55-11e9-96ee-e060bf801bed.gif)
Colombia: ![colombia](https://user-images.githubusercontent.com/46827621/53676351-e4cc6d00-3c55-11e9-9801-c390cfbabb79.gif)
Albania: ![albania](https://user-images.githubusercontent.com/46827621/53676352-e4cc6d00-3c55-11e9-85ab-ea126f30a9db.gif)
Cyprus: ![cyprus](https://user-images.githubusercontent.com/46827621/53676353-e5650380-3c55-11e9-9e02-1e5a54aed34e.gif)
Moldova: ![moldova](https://user-images.githubusercontent.com/46827621/53676354-e5650380-3c55-11e9-97a7-8634fc6cac69.gif)
North Macedonia: ![northmacedonia](https://user-images.githubusercontent.com/46827621/53676355-e5650380-3c55-11e9-8966-59399a70fcc2.gif)
Greek Macedonia: ![greekmacedonia](https://user-images.githubusercontent.com/46827621/53676356-e5650380-3c55-11e9-9086-090752a9c4b0.gif)
Kosovo: ![kosovo](https://user-images.githubusercontent.com/46827621/53676357-e5650380-3c55-11e9-893a-eb2c1437d3e5.gif)
Bosnia and Herzgovina: ![bosniaandherzegovina](https://user-images.githubusercontent.com/46827621/53676358-e5650380-3c55-11e9-9281-f3eb5cb403bd.gif)
Montenegro: ![montenegro](https://user-images.githubusercontent.com/46827621/53676359-e5fd9a00-3c55-11e9-8c98-bfe6ad9889b3.gif)
Bulgaria: ![bulgaria](https://user-images.githubusercontent.com/46827621/53676360-e5fd9a00-3c55-11e9-9453-aaca596f2a39.gif)
Croatia: ![croatia](https://user-images.githubusercontent.com/46827621/53676361-e5fd9a00-3c55-11e9-8e20-6c9e5477a8b5.gif)

**Comment by jmhobbs** [comment]
Added!
