### ISSUE TITLE
Missing Nigeria Parrot

### ISSUE THREAD

**Issue by MavenRain** [jmhobbs/cultofthepartyparrot.com#322]
Could you add a Nigeria Parrot?

**Comment by uberchemist** [comment]
Yes, I plan to fill out all the major African countries next! (Just finished South America.) But, just for you, here's Nigeria!
Nigeria Parrot: ![nigeria](https://user-images.githubusercontent.com/46827621/53744644-43f6d100-3e52-11e9-9daf-7d9d1d0e3fd5.gif)

**Comment by jmhobbs** [comment]
Nice!  I'll get it added to the site.

**Comment by jmhobbs** [comment]
Uploaded and on the site.  Thanks @uberchemist!
