### ISSUE TITLE
African Killer Parrots!

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#328]
I've completed most of the large African countries. From this point going forward, I plan to round out the remaining countries alphabetically, referencing Wikipedia's [List of sovereign states](https://en.wikipedia.org/wiki/List_of_sovereign_states). So, be on the lookout for a new issue "A-B", etc.

Sudan: ![sudan](https://user-images.githubusercontent.com/46827621/53837265-0d4eb280-3f47-11e9-86c4-648a07018c92.gif)
Cameroon: ![cameroon](https://user-images.githubusercontent.com/46827621/53837270-0f187600-3f47-11e9-86ae-c6ca5631fe5f.gif)
Central African Republic: ![centralafricanrepublic](https://user-images.githubusercontent.com/46827621/53837273-12136680-3f47-11e9-90ea-c172f3dc02dc.gif)
South Sudan: ![southsudan](https://user-images.githubusercontent.com/46827621/53837275-13dd2a00-3f47-11e9-9fb8-9866bcfc5939.gif)
Ethiopia: ![ethiopia](https://user-images.githubusercontent.com/46827621/53837278-16d81a80-3f47-11e9-88b2-b4936869995f.gif)
Somalia: ![somalia](https://user-images.githubusercontent.com/46827621/53837282-18a1de00-3f47-11e9-96aa-fe18c1581ca3.gif)
Kenya: ![kenya](https://user-images.githubusercontent.com/46827621/53837283-1b043800-3f47-11e9-9c43-eca3d933d800.gif)
Uganda: ![uganda](https://user-images.githubusercontent.com/46827621/53837287-1d669200-3f47-11e9-921b-c6aa9e50c5b3.gif)
Democratic Republic of the Congo: ![democraticrepublicofthecongo](https://user-images.githubusercontent.com/46827621/53837297-1f305580-3f47-11e9-968d-677c25cca6eb.gif)
Republic of the Congo: ![republicofthecongo](https://user-images.githubusercontent.com/46827621/53837301-2192af80-3f47-11e9-8d95-4ce3c739cde9.gif)
Gabon: ![gabon](https://user-images.githubusercontent.com/46827621/53837305-235c7300-3f47-11e9-9a5f-25adff22c30c.gif)
Rwanda: ![rwanda](https://user-images.githubusercontent.com/46827621/53837308-25263680-3f47-11e9-821c-9b8adde736dc.gif)
Burundi: ![burundi](https://user-images.githubusercontent.com/46827621/53837310-26effa00-3f47-11e9-91ac-d69f57f8db1b.gif)
Tanzania: ![tanzania](https://user-images.githubusercontent.com/46827621/53837315-29525400-3f47-11e9-8b73-28a18597259e.gif)
Angola: ![angola](https://user-images.githubusercontent.com/46827621/53837318-2b1c1780-3f47-11e9-9ab2-8aab570f2de4.gif)
Zambia: ![zambia](https://user-images.githubusercontent.com/46827621/53837323-2d7e7180-3f47-11e9-9809-fc4d3de42ad4.gif)
Malawi: ![malawi](https://user-images.githubusercontent.com/46827621/53837329-2f483500-3f47-11e9-9e1a-f8d704817cc2.gif)
Mozambique: ![mozambique](https://user-images.githubusercontent.com/46827621/53837334-3111f880-3f47-11e9-9090-3e633031af94.gif)
Zimbabwe: ![zimbabwe](https://user-images.githubusercontent.com/46827621/53837338-32dbbc00-3f47-11e9-8efb-d2f7fb76eebc.gif)
Namibia: ![namibia](https://user-images.githubusercontent.com/46827621/53837342-353e1600-3f47-11e9-9e2e-beffc7b5d491.gif)
Botswana: ![botswana](https://user-images.githubusercontent.com/46827621/53837349-3707d980-3f47-11e9-8584-be96fba33c62.gif)
Eswatini: ![eswatini](https://user-images.githubusercontent.com/46827621/53837350-396a3380-3f47-11e9-8292-f7ba66ab27cf.gif)
Lesotho: ![lesotho](https://user-images.githubusercontent.com/46827621/53837353-3b33f700-3f47-11e9-8e85-d094b687a488.gif)
Madagascar: ![madagascar](https://user-images.githubusercontent.com/46827621/53837355-3cfdba80-3f47-11e9-86b0-dffa62fbf0ed.gif)

**Comment by jmhobbs** [comment]
Those are some cool flags.  Thanks, I'll get these up!

**Comment by jmhobbs** [comment]
Whoops! Missed these in the last PR. So many flags!

**Comment by uberchemist** [comment]
IKR! But they sure look sweet all together!

The colors, man... the colors!!
