### ISSUE TITLE
HD Flag Parrots Leftovers: T-Z and Other States **Project Complete!**

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#332]
### **This completes the Flag Parrot Project! Whew!**

Tajikistan: ![tajikistan](https://user-images.githubusercontent.com/46827621/54040921-5b4bfc00-417b-11e9-9850-1d586f0ce402.gif)
Togo: ![togo](https://user-images.githubusercontent.com/46827621/54040923-5d15bf80-417b-11e9-994d-529faf70b417.gif)
Tonga: ![tonga](https://user-images.githubusercontent.com/46827621/54040928-5f781980-417b-11e9-9402-b5930ad9c451.gif)
Tunisia: ![tunisia](https://user-images.githubusercontent.com/46827621/54040937-62730a00-417b-11e9-990e-43f106d6016a.gif)
Turkey: ![turkey](https://user-images.githubusercontent.com/46827621/54040943-643ccd80-417b-11e9-87ea-b5a7ccd18cb5.gif)
Turkmenistan: ![turkmenistan](https://user-images.githubusercontent.com/46827621/54040949-66069100-417b-11e9-8f9f-7f3f661c1a4d.gif)
Tuvalu: ![tuvalu](https://user-images.githubusercontent.com/46827621/54040954-69018180-417b-11e9-97ad-8a04da3bcb5d.gif)
United Arab Emirates: ![unitedarabemirates](https://user-images.githubusercontent.com/46827621/54040958-6acb4500-417b-11e9-9cf5-d98df8426e40.gif)
Uzbekistan: ![uzbekistan](https://user-images.githubusercontent.com/46827621/54040965-6d2d9f00-417b-11e9-9184-a1046950fd57.gif)
Vanuatu: ![vanuatu](https://user-images.githubusercontent.com/46827621/54040971-6ef76280-417b-11e9-864f-25474dc42b23.gif)
Vatican City: ![vaticancity](https://user-images.githubusercontent.com/46827621/54040975-7159bc80-417b-11e9-86ba-ef3ec53831c7.gif)
Yemen: ![yemen](https://user-images.githubusercontent.com/46827621/54040982-73bc1680-417b-11e9-9326-9370f201612a.gif)

_The following are listed as "other states" as they are either claimed by other countries, or not officially recognized by many, or whose sovereignty in general is disputed. Including them here because it's a short list!_
Abkhazia: ![abkhazia](https://user-images.githubusercontent.com/46827621/54043253-f98e9080-4180-11e9-8415-f208b2d664ec.gif)
Artsakh: ![artsakh](https://user-images.githubusercontent.com/46827621/54043257-fb585400-4180-11e9-98d2-b35d08090a7e.gif)
Cook Islands: ![cookislands](https://user-images.githubusercontent.com/46827621/54043259-fd221780-4180-11e9-9615-8b776253fdc3.gif)
Niue: ![niue](https://user-images.githubusercontent.com/46827621/54043261-ff847180-4180-11e9-9ba1-55b2c9307f42.gif)
Northern Cyprus: ![northerncyprus](https://user-images.githubusercontent.com/46827621/54043265-014e3500-4181-11e9-91f5-6ef05cc1f7a8.gif)
Sahrawi Arab Democratic Republic: ![sahrawiarabdemocraticrepublic](https://user-images.githubusercontent.com/46827621/54043271-04e1bc00-4181-11e9-8b56-8f0ae564a1de.gif)
Somaliland: ![somaliland](https://user-images.githubusercontent.com/46827621/54043275-07441600-4181-11e9-9a25-d07bf7d66ba9.gif)
South Ossetia: ![southossetia](https://user-images.githubusercontent.com/46827621/54043279-09a67000-4181-11e9-9171-64b077a29abf.gif)
Transnistria: ![transnistria](https://user-images.githubusercontent.com/46827621/54043283-0b703380-4181-11e9-8344-874d5ea16c70.gif)

**Comment by jmhobbs** [comment]
Amazing!  Thank you for all your hard work, I'll get everything up soon.
