### ISSUE TITLE
Crowdsourcing name for new parrot!

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#333]
Here it is:

![horizontal](https://user-images.githubusercontent.com/46827621/54214860-366dc680-44a4-11e9-8a7a-3e04619a1947.gif)

My thoughts were "Horizontal Parrot" or "Level Parrot" but open to anything better!

**Comment by cavpollo** [comment]
Horizontal sounds good to me. If a raised wing (finger) was added, it could transform into [Sassy Parrot](https://media.giphy.com/media/CmZ5FXzzFfOy4/giphy.gif) xD

**Comment by magnuspaaske** [comment]
Horozontal seems a good name, but now that it's been brought up I think we definitely need Sassy Parrot

**Comment by jmhobbs** [comment]
We've got a sassy parrot already.

https://cultofthepartyparrot.com/parrots/hd/sassyparrot.gif
