### ISSUE TITLE
Portal Parrots Remake

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#341]
I wanted to remake the portal parrots as I ❤️ the game so much, and really wanted these to be in full HD!

Orange Portal: ![portal-orange](https://user-images.githubusercontent.com/46827621/54394758-07558180-466b-11e9-8ab8-a10149d98ca9.gif)

Blue Portal: ![portal-blue](https://user-images.githubusercontent.com/46827621/54394762-0a507200-466b-11e9-9a05-464c2b4a46dc.gif)

Let me know what you think!

**Comment by cavpollo** [comment]
What always bothered me about the portal gifs is that they are not exactly synchronized, in the sense that as the parrot steps inside the portal it should be coming out of the other one at the same time... because that's how portals work, right? :sweat_smile:

**Comment by v00d00** [comment]
Yeah one parrot should be half way out as the other is half way in

**Comment by uberchemist** [comment]
I tried to get that timing better synchronized, but I also noticed that it can also depend on when each GIF gets loaded... so if the second portal GIF loads a split second later than the first, the synchronization will be off. But I'll see if I can tweak this a bit more anyway.

**Comment by cavpollo** [comment]
That's true, but usually, if they are synced, once they been loaded to memory and the page (or whatever platform is used) is refreshed, they should look just fine =)

**Comment by uberchemist** [comment]
Synchronization Test 1:

![portal-orange](https://user-images.githubusercontent.com/46827621/54462092-d1c49d00-472b-11e9-8199-7b65734c18e5.gif)
![portal-blue](https://user-images.githubusercontent.com/46827621/54462096-d38e6080-472b-11e9-858c-3a169f3659a0.gif)

If I did the math right, the same parrot frame should appear in the middle of each portal at the exact same time.

**Comment by cavpollo** [comment]
Looks great to me :grin:

**Comment by v00d00** [comment]
These look amazing
