### ISSUE TITLE
Missing flag: Antarctica!

### ISSUE THREAD

**Issue by EctoCool** [jmhobbs/cultofthepartyparrot.com#345]
This is the flag you want for Antarctica: https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_the_Antarctic_Treaty.svg

**Comment by uberchemist** [comment]
Good call! I'm on it!

**Comment by uberchemist** [comment]
![antarctica](https://user-images.githubusercontent.com/46827621/54622060-13a05c80-4a26-11e9-8223-7aee57c3460e.gif)
