### ISSUE TITLE
Original author

### ISSUE THREAD

**Issue by fstanis** [jmhobbs/cultofthepartyparrot.com#348]
Just saw in the license:

https://github.com/jmhobbs/cultofthepartyparrot.com/blob/3eacd5293a1b4e9509ceeecee91a1d9025d72660/LICENSE#L1

It seems the original author is Geiger Powell per [this Mashable article](https://mashable.com/article/party-parrot-creator/). Maybe we can reach out to him to clarify on the licensing for the parrot?

**Comment by jmhobbs** [comment]
Awesome!  Anyone find a way to reach out to him?  I'm not in the something awful forums and I can't find a reliable looking contact online.  If you've got a lead, DM me on Twitter or else shoot me an email.

**Comment by jmhobbs** [comment]
Nevermind, I'll try to get in touch through the podcast in the article.

**Comment by jmhobbs** [comment]
Updated!
