### ISSUE TITLE
Rename & Relocate Parrots

### ISSUE THREAD

**Issue by Darth-Arminius** [jmhobbs/cultofthepartyparrot.com#349]
Looking through the parrots while uploading them to Slack, I noticed a couple of inconsistencies with naming. As the number of parrots grow it's probably a good idea to make sure the naming is consistent, especially when it comes to bulk uploading them onto something like Slack.

The below parrots have inconsistent names:

- `flower_parrot` - remove underscore to `flowerparrot`

- `frenchparrothd` - remove the "hd" to make `frenchparrot`

- `parrotbeer` - make the "parrot" bit the suffix `beerparrot`

- `parrotcop` - make the "parrot" bit the suffix `copparrot`

- `parrotmustache` - make the "parrot" bit the suffix `mustacheparrot`

- `parrotdad` - this works but for consistency it could be renamed to `dadparrot` if preferred

- `parrotsleep` - this also kind of works but again could be renamed to `asleepparrot` or equivalent

- `rightparrot` - based on previous "reverseXparrot" this should be `reverseparrot`

- `ice-cream-parrot` - remove second or both hyphens to either `ice-creamparrot` or `icecreamparrot`

- `upvotepartyparrot` - "partyparrot" is a specific type of parrot whereas this refers to the standard parrot with the addition of the upvote so should be named `upvoteparrot`

There are also six HD parrots that are currently in the standard non-HD folder and should be moved over to the HD folder:

- brazilianfanparrot

- brazilianplayerparrot

- evilparrot

- githubparrot

- invisibleparrot

- spyparrot

If you guys agree with all/some of the above changes I'll go ahead and fire up a pull request. If a naming convention/standard is agreed on, a further pull request can be created to document the naming style in the "Contributing" section of the README.

**Comment by jmhobbs** [comment]
All good points, go for it!

**Comment by jmhobbs** [comment]
Closing this issue, thanks for the fixes!
