### ISSUE TITLE
Sherlock Parrot - plus some others

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#352]
Here's a new one to add:

Sherlock Parrot: ![sherlock](https://user-images.githubusercontent.com/46827621/55189619-8bbffe00-515b-11e9-9a86-4887675b35bb.gif)

Also, a couple HD replacements not yet on the site:

Aussie Parrot: ![aussie](https://user-images.githubusercontent.com/46827621/55189745-bf028d00-515b-11e9-86cf-77a9ea37fad9.gif)
Witness Protection Parrot: ![witnessprotection](https://user-images.githubusercontent.com/46827621/55189756-c3c74100-515b-11e9-8abe-5fa1255c7803.gif)

Finally, a couple other "party guests" I found on the interwebs... no idea about rules regarding parrots made elsewhere...

Try Not to Cry: ![trynottocry](https://user-images.githubusercontent.com/46827621/55189809-dc375b80-515b-11e9-9066-0672a6a1265d.gif)
Blob: ![blob](https://user-images.githubusercontent.com/46827621/55189822-e2c5d300-515b-11e9-9545-ab86806a2a00.gif)

**Comment by jmhobbs** [comment]
Nice!  Generally I like to have the creator of things add them, so I may wait on those.  Man that blob is a good one though!

**Comment by jmhobbs** [comment]
Looks like the blob comes from https://discord.me/blobemoji and is APL 2.0 licensed.  https://blobs.gg/

I'll add that one too, it's a good one.
