### ISSUE TITLE
Please Add Original Parrot

### ISSUE THREAD

**Issue by lambdaknight** [jmhobbs/cultofthepartyparrot.com#354]
Please add plain green, original party parrot emote. See https://i.somethingawful.com/forumsystem/emoticons/emot-parrot.gif

**Comment by uberchemist** [comment]
I created the HD version: ![original](https://user-images.githubusercontent.com/46827621/59626386-9b166e00-90f0-11e9-91c3-f8cc6c139b07.gif)
