### ISSUE TITLE
I created a party parrot kernel module in Rust

### ISSUE THREAD

**Issue by jbaublitz** [jmhobbs/cultofthepartyparrot.com#364]
I have a [kernel module](https://github.com/jbaublitz/knock-out) that I'd like to incorporate into this repo somehow. The frames are taken from `parrot.live`. It creates a char device where `cat` can be run on the device node and it starts a party parrot animation in your terminal. Given that this doesn't have any kind of application beyond "oh, that's kinda neat!", this is the repo I seem to have been looking for all along without even realizing it. Would you be open to incorporating it somehow?

**Comment by jmhobbs** [comment]
What.  That is amazing.

I'd love to link to it from the site, but the repo is a bit opaque when you first land on it.  Do you think you could add a bit to the README to make it more readily apparent what is going on?

**Comment by jbaublitz** [comment]
I can totally do that! I'll ping you here once that's updated for sure. Thanks!

**Comment by jbaublitz** [comment]
The README has more information now. Is there anything you want me to add or does that look like what you were hoping for?

**Comment by jmhobbs** [comment]
Perfect!  I'll get it added as a link.
