### ISSUE TITLE
New Party Guest

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#368]
Party Keanu: ![keanu](https://user-images.githubusercontent.com/46827621/60906538-37cdb680-a22c-11e9-8a1d-17d96089f0f6.gif)

"Whoever comes, whoever it is... I'll party with them."

**Comment by jmhobbs** [comment]
![its-beautiful](https://user-images.githubusercontent.com/115059/60907068-40c78380-a23e-11e9-842d-41a503f74340.gif)
