### ISSUE TITLE
Add Vertical Parrot

### ISSUE THREAD

**Issue by Some1NamedNate** [jmhobbs/cultofthepartyparrot.com#371]

**Comment by uberchemist** [comment]
I've already pondered this one... still not quite sure how I'll do it... thought about just rotating the horizontal parrot 90° but that's *cheep*. I'm on it, though!

**Comment by Some1NamedNate** [comment]
Thanks so much!

**Comment by uberchemist** [comment]
Vertical Parrot: ![vertical](https://user-images.githubusercontent.com/46827621/62253785-ec7e7200-b3ab-11e9-8646-104bc0af48e1.gif)

**Comment by cavpollo** [comment]
Bahahaha, not sure if this follows the right definition of "vertical", but man, it is gold xD

**Comment by Some1NamedNate** [comment]
What I mean by Vertical Parrot is a counterpart of Horizontal Parrot (https://cultofthepartyparrot.com/parrots/hd/horizontalparrot.gif)

**Comment by jmhobbs** [comment]
@uberchemist I love that parrot!

@Some1NamedNate do you mean the horizontal parrot, but rotated 90°?

**Comment by uberchemist** [comment]
@jmhobbs Thanks!
@Some1NamedNate Please elaborate!

**Comment by uberchemist** [comment]
Also, this:
**ver·ti·cal**
at right angles to a horizontal plane; in a direction, or having an alignment, such that the top is directly above the bottom.

**Comment by jmhobbs** [comment]
My thinking is that what @uberchemist submitted should be vertical parrot, and if we do one where it is rotated 90° it'll be either up parrot or down parrot (based on which way it's "facing").

Thoughts?

**Comment by Some1NamedNate** [comment]
Technically speaking, you know how Horizontal Parrot restricts the Parrot's head's movement to the x-axis? Vertical Parrot should restrict the Parrot's head's movement to the y-axis.

Makes sense?

**Comment by francoislg** [comment]
> Vertical Parrot: ![vertical](https://user-images.githubusercontent.com/46827621/62253785-ec7e7200-b3ab-11e9-8646-104bc0af48e1.gif)

Might I suggest an alt title for this one? :)

"Bouncing Parrot"

**Comment by jmhobbs** [comment]
@Some1NamedNate I gotta be honest, based on your comment, I feel like what @uberchemist made there is spot on.  We need, like, a diagram or something, I'm not getting it, sorry 🙁

**Comment by Some1NamedNate** [comment]
Let me put this "diagram" to words, then.

The Party Parrot's head moves in a circle; the x and y axes are involved. ( ![](https://cultofthepartyparrot.com/parrots/hd/parrot.gif) )

For Stable Parrot, both the x and y axes are removed. ( ![](https://cultofthepartyparrot.com/parrots/hd/stableparrot.gif) )

For Horizontal Parrot, the y axis is removed, causing the Parrot's head to move left and right. ( ![](https://cultofthepartyparrot.com/parrots/hd/horizontalparrot.gif) )

For Vertical Parrot, if we remove the x axis, the Parrot's head should move up and down only.

Do you get what I'm trying to say thus far?

**Comment by jmhobbs** [comment]
Ok, I think this just clicked for me.  Is this what you mean?

![vertical-parrot](https://user-images.githubusercontent.com/115059/62481625-88c3c280-b778-11e9-8bb3-c5908b4bd256.gif)

**Comment by uberchemist** [comment]
@jmhobbs I'd call that Levitation Parrot!

**Comment by uberchemist** [comment]
Need some resolution from the community!! Make it end!!

> 
> 
> Let me put this "diagram" to words, then.
> 
> The Party Parrot's head moves in a circle; the x and y axes are involved. ( ![](https://camo.githubusercontent.com/84d12da81bcc863abf935a3713930ced7a3c7e62/68747470733a2f2f63756c746f667468657061727479706172726f742e636f6d2f706172726f74732f68642f706172726f742e676966) )
> 
> For Stable Parrot, both the x and y axes are removed. ( ![](https://camo.githubusercontent.com/798b59b7f6567ecfe80332b28ee2005b5b642696/68747470733a2f2f63756c746f667468657061727479706172726f742e636f6d2f706172726f74732f68642f737461626c65706172726f742e676966) )
> 
> For Horizontal Parrot, the y axis is removed, causing the Parrot's head to move left and right. ( ![](https://camo.githubusercontent.com/3c2c6bdaf5e646afb356a515145e6ae561f62e4f/68747470733a2f2f63756c746f667468657061727479706172726f742e636f6d2f706172726f74732f68642f686f72697a6f6e74616c706172726f742e676966) )
> 
> For Vertical Parrot, if we remove the x axis, the Parrot's head should move up and down only.
> 
> Do you get what I'm trying to say thus far?

The problem with this is that the vertical movement of the parrot's head is quite small, relatively speaking. Note also that the parrot's body moves significantly left to right. It's hard to isolate these two and create a similar version to the horizontal parrot. But it can be done.

**Comment by uberchemist** [comment]
Okay, everyone. I spent more time on this and made the version that I believe @Some1NamedNate is looking for. I was skeptical about how it would turn out, but now that I see it in action, I actually quite like it! It's got more of a "head bob" going for it compared with my first attempt's "ramming" style.
![vertical_v2](https://user-images.githubusercontent.com/46827621/64543974-04b2ac80-d2db-11e9-9dd5-f0e4a970fea0.gif)
Let me know what you guys think! From all this, I think we've managed to create a vertical parrot, bouncing parrot and levitation parrot!

**Comment by Some1NamedNate** [comment]
That is _exactly_ what I'm looking for, @uberchemist . That appears to be a beta image; if so, I understand that. A bit of fine-tuning would be nice. Otherwise, I could/would close this issue.

**Comment by jmhobbs** [comment]
Whoa.

**Comment by Some1NamedNate** [comment]
Correction: I _can_ close this issue.

**Comment by jmhobbs** [comment]
I'm going to add in @uberchemist's version, and if any revisions happen we can merge those later.
