### ISSUE TITLE
Backwards Parrot (HD)

### ISSUE THREAD

**Issue by Some1NamedNate** [jmhobbs/cultofthepartyparrot.com#376]
![backwardsparrot](https://user-images.githubusercontent.com/33171016/62812712-d06d8580-babb-11e9-8e23-ea56483ba9ff.gif)

**Comment by jmhobbs** [comment]
Nice!  Will get this patched in.

**Comment by Some1NamedNate** [comment]
🥳

**Comment by jmhobbs** [comment]
Thanks!
