### ISSUE TITLE
New Funkalicious HD Replacement: Party Fieri

### ISSUE THREAD

**Issue by uberchemist** [jmhobbs/cultofthepartyparrot.com#386]
You never knew you wanted this until now...
![fieri](https://user-images.githubusercontent.com/46827621/63950029-20db6180-ca30-11e9-9e81-103ade39901b.gif)
Welcome to Flavortown!

EDIT: Also, I'm suggesting the name be updated from "Guy Fieri Parrot" to "Party Fieri" to keep with the recent trend of celeb parrots using "Party [Name]".

**Comment by jmhobbs** [comment]
![its-beautiful](https://user-images.githubusercontent.com/115059/63954663-0feb1a00-ca49-11e9-91fe-eb6352cd4f7b.gif)
