### ISSUE TITLE
Remove cursor change on HD span

### ISSUE THREAD

**Issue by donnavitan** [jmhobbs/cultofthepartyparrot.com#402]
Can we remove the cursor change for accessibility consideration, and that it's unnecessary on non-interactive elements?

**Comment by jmhobbs** [comment]
Sure, that makes sense!  Would you like to submit that change or shall I take care of it?

**Comment by donnavitan** [comment]
I'd love to do it!

**Comment by donnavitan** [comment]
I did the thing! I know it was pretty simple and may be trivial but I do appreciate letting me go through the whole process. I love learning and getting used to the process of this whole Github thing! https://github.com/jmhobbs/cultofthepartyparrot.com/pull/404

I'll leave it to you @jmhobbs to close?

**Comment by jmhobbs** [comment]
Perfect! Thanks for contributing!
