### ISSUE TITLE
Request: Hmmm Parrot

### ISSUE THREAD

**Issue by shan916** [jmhobbs/cultofthepartyparrot.com#425]
It would be awesome to have a Hmmm parrot. Confused parrot doesn't cut it. Need the hmmm parrot for when you're thinking about something.

**Comment by faverolles** [comment]
I was making some mock ups just for kicks. What do you think of this?
[Thinking Face On Different Platforms](https://emojipedia.org/thinking-face/)
Does it look too much like parrot is making a finger gun?
![hmm](https://user-images.githubusercontent.com/48035185/80777541-3bb82580-8b2b-11ea-8e23-7e1fc8356166.png)

**Comment by shan916** [comment]
Maybe make the angle between the thumb and finger just a little smaller? Other than that, looks great to me.

**Comment by jmhobbs** [comment]
I _LOVE_ this.  I use 🤔 all the time.

**Comment by shan916** [comment]
@faverolles you might need some modifications to support dark mode. @jmhobbs I think you added a white outline to the text for the confused parrot. Same approach might work here.

**Comment by faverolles** [comment]
@shan916 Very good point, and good idea. I was thinking of doing the text color-changing as well so I'll be sure to check against light and dark backgrounds.

**Comment by jmhobbs** [comment]
Closed by #469 and 254c738
