### ISSUE TITLE
Confused Parrot doesn't render properly in Slack in dark mode

### ISSUE THREAD

**Issue by shan916** [jmhobbs/cultofthepartyparrot.com#426]
When dark mode is enabled in Slack, the question marks on the confused parrot do not appear.

**Comment by jmhobbs** [comment]
Good catch!  I wonder if we should outline those with a little white, that way it should work on any background.

**Comment by edhansen42** [comment]
@jmhobbs That's a great idea!  
![shipitparrot](https://user-images.githubusercontent.com/4911306/69989163-e504dc00-14f7-11ea-8810-b5a82b19eacd.gif)

**Comment by shan916** [comment]
@jmhobbs 
![shipitparrot](https://user-images.githubusercontent.com/4755022/69989210-fcdc6000-14f7-11ea-9de0-13c255a92a21.gif) ![shipitparrot](https://user-images.githubusercontent.com/4755022/69989210-fcdc6000-14f7-11ea-9de0-13c255a92a21.gif) ![shipitparrot](https://user-images.githubusercontent.com/4755022/69989210-fcdc6000-14f7-11ea-9de0-13c255a92a21.gif) ![shipitparrot](https://user-images.githubusercontent.com/4755022/69989210-fcdc6000-14f7-11ea-9de0-13c255a92a21.gif) ![shipitparrot](https://user-images.githubusercontent.com/4755022/69989210-fcdc6000-14f7-11ea-9de0-13c255a92a21.gif) ![shipitparrot](https://user-images.githubusercontent.com/4755022/69989210-fcdc6000-14f7-11ea-9de0-13c255a92a21.gif)

**Comment by jmhobbs** [comment]
Hopefully that works ok for everyone 👍
