### ISSUE TITLE
Request: Pirate pirate

### ISSUE THREAD

**Issue by SanderSander** [jmhobbs/cultofthepartyparrot.com#43]
What's a pirate without parrot?? A pirate parrot! aaarrrr! 

It would be awesome to have a pirate parrot.

**Comment by jmhobbs** [comment]
Arrrrgggghhhh!

**Comment by SanderSander** [comment]
Is there a modern tool to edit animated gifs?? because I probably can do it myself (it's like 10 years ago for me) ;)

**Comment by jmhobbs** [comment]
I use Gimp and gifsicle ¯\_(シ)_/¯

**Comment by kbvincent** [comment]
![pirateparrot](https://cloud.githubusercontent.com/assets/4335456/20849695/ebcb32c0-b8a5-11e6-908d-9e11b511b331.gif)

**Comment by jmhobbs** [comment]
Sword in there maybe?  Might be too cluttered with that.

**Comment by kbvincent** [comment]
![pirate_parrot_w_sword](https://cloud.githubusercontent.com/assets/4335456/20856165/a5fa6974-b8d6-11e6-877c-f9ace3495141.gif)

**Comment by mrkolby** [comment]
This can be closed: https://github.com/jmhobbs/cultofthepartyparrot.com/pull/185

**Comment by melinerunen** [comment]
@jmhobbs #185 !!!
