### ISSUE TITLE
Coronaparrot

### ISSUE THREAD

**Issue by cscashby** [jmhobbs/cultofthepartyparrot.com#437]
I feel this parrot needs to be more publicly available given the current climate ...
![coronaparrot](https://user-images.githubusercontent.com/1113694/76439985-1b82aa80-63b5-11ea-9ed4-d071d11cc09a.gif)

**Comment by melinerunen** [comment]
I suggest using the Bored parrot as a base since the virus is not meant to be a party. Alternative add the white mask using the party parrot as a base :)

**Comment by jmhobbs** [comment]
I'm not sure how I feel about this one.  I think I'd be game for a "mask parrot" or the like, perhaps with a white surgical mask, but I don't think I want to have a party parrot for a virus.

**Comment by cscashby** [comment]
Bored version...
![boredvirusparrot](https://user-images.githubusercontent.com/1113694/76441469-5daceb80-63b7-11ea-840b-cd07a634aafa.gif)

**Comment by cscashby** [comment]
@jmhobbs that's fair. Maybe doc/nurse parrot or something to make it a bit less obvious...

**Comment by cscashby** [comment]
Docparrot
![docparrot](https://user-images.githubusercontent.com/1113694/76442828-66062600-63b9-11ea-9054-32b17d7b9f9f.gif)

**Comment by jmhobbs** [comment]
Yes!  I like that much better.  Can you open a PR or would you like me to do it?

**Comment by cscashby** [comment]
I'm a bit of a parrot newbie so don't know the process - if there's a way of generating a hires parrot I can do that :)

**Comment by jmhobbs** [comment]
I don't think that there is a tool for HD ones like there is for the regular size, so that'll have to be a manual thing.   We can put in the non-HD for now and then make an issue for someone to add the HD when they have time.  I'll open a PR!

**Comment by cscashby** [comment]
Thanks :) My work on the internet is done.
