### ISSUE TITLE
Request: Coronavirus parrot

### ISSUE THREAD

**Issue by albertvaka** [jmhobbs/cultofthepartyparrot.com#443]
Face mask parrot would  be nice as well.

**Comment by jmhobbs** [comment]
We merged #438 a few days ago, so that one has a face mask.  Not sure what a Coronavirus parrot would look like.  Honestly, it's not a very party thing, kind of a downer really.  Open to ideas though!

**Comment by albertvaka** [comment]
I was imagining a parrot with 🦠 as a face, but doctor parrot is good enough 👌

**Comment by johnjenkman** [comment]
#447 was recently merged to add a COVID-19 parrot.
