### ISSUE TITLE
parrot wave out of order

### ISSUE THREAD

**Issue by amc6** [jmhobbs/cultofthepartyparrot.com#45]
It seems like the parrot wave is out of order and doesn't sync up properly. Its seems like the right order is 4 5 6 1 2 3 4. Anyone else seeing this?

**Comment by amc6** [comment]
cc @lucymhdavies

**Comment by amc6** [comment]
Never mind. It looks like this is a slack issue. At least in their import emoji viewer, the gif start times are not synced. So the wave wont necessarily be in the right order.

**Comment by jmhobbs** [comment]
Yeah, it happens with slack sometimes unfortunately.  Sorry!

**Comment by amc6** [comment]
![Sad Parrot](http://cultofthepartyparrot.com/parrots/sadparrot.gif)

**Comment by gallak87** [comment]
For anyone who finds this issue, I believe slack doesn't re-render even when posting for some reason.. But if you quit slack and re-open, the wave parrots previously posted wave in order
