### ISSUE TITLE
Request: England, Scotland, Wales and Northern Ireland parrot flags

### ISSUE THREAD

**Issue by johnjenkman** [jmhobbs/cultofthepartyparrot.com#451]
There is currently a United Kingdom parrot. However, the UK is made up of four countries England, Scotland, Wales and Northern Ireland.

It would be nice to have a dedicated parrot for each country.

**Comment by jmhobbs** [comment]
An excellent distinction! Maybe @uberchemist will come to the rescue!

**Comment by uberchemist** [comment]
I would be happy to, but you've opened up a [can of worms](https://en.wikipedia.org/wiki/Northern_Ireland_flags_issue) regarding the flag of Northern Ireland.
TLDR: there is no official flag for Northern Ireland; the Union Jack is considered the de facto flag and flown at local government buildings.

**Comment by uberchemist** [comment]
Okay, I took the easy route so we can close this: I've created the parrots for England, Scotland, Wales and made the two most common alternatives for N. Ireland. If people have issues with that, let them be raised and we'll deal with it at that point!

![england](https://user-images.githubusercontent.com/46827621/77786970-fe3c1600-701b-11ea-8585-b86ba498b1ea.gif) England

![scotland](https://user-images.githubusercontent.com/46827621/77786983-0431f700-701c-11ea-9a16-85a40d731fcd.gif) Scotland

![wales](https://user-images.githubusercontent.com/46827621/77787000-0ac06e80-701c-11ea-9c88-a68898cdd23a.gif) Wales

![northernirelandsaintpatrickssaltire](https://user-images.githubusercontent.com/46827621/77787018-11e77c80-701c-11ea-844d-7257268f1fca.gif) Northern Ireland: Saint Patrick's Saltire

![northernirelandulsterbanner](https://user-images.githubusercontent.com/46827621/77787027-157b0380-701c-11ea-9ade-67b0491707f8.gif) Northern Ireland: Ulster Banner

**Comment by jmhobbs** [comment]
Thank you @uberchemist, and thanks for your awareness of these sorts of things!  I'll get a PR up.

**Comment by johnjenkman** [comment]
Thanks for the quick turnaround folks 👍
