### ISSUE TITLE
Replace broken tshirt links

### ISSUE THREAD

**Issue by parroteer** [jmhobbs/cultofthepartyparrot.com#467]
Broken tshirt links should be replaced. Found alternative working links with same graphics:

https://www.redbubble.com/i/t-shirt/Party-Parrot-from-Slack-in-HD-by-minimalismlab/47571657.WFLAH

https://www.redbubble.com/i/t-shirt/Party-Parrot-Triplets-from-Slack-emoticon-by-fontart/47572373.WFLAH

**Comment by jmhobbs** [comment]
I will unlink those instead because they are out of print.  Unsure if the triplets parrot on red bubble is violating a license or released by the original designer, so I won't be linking that one.
