### ISSUE TITLE
Adding a new Party Parrot tool

### ISSUE THREAD

**Issue by AnimeshAgrawal** [jmhobbs/cultofthepartyparrot.com#497]
Hi folks, I'm working on a CLI tool that'll take in a folder of pictures (team group pictures or individual profile pictures etc) and generate a party parrot for each face in the input pictures. I originally built this so my org could give everyone their own party parrot, but I'd like to contribute it to the cult (as one of the links at the bottom of the page) so other people can use it too. Is this an acceptable contribution, and if so, how would I go about the PR review process for it? Thanks!

**Comment by jmhobbs** [comment]
That sounds amazing!  The template for the index page is here: https://github.com/jmhobbs/cultofthepartyparrot.com/blob/master/templates/index.html

You can edit that, add a link to your tool, open a PR and we'll merge it up!

**Comment by zoidbergwill** [comment]
It looks like it lives here https://github.com/AnimeshAgrawal/partyparrot-team
