### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#512]
Lots of transparent backgrounds, let's add a dark mode!

**Comment by jmhobbs** [comment]
Bonus points for respecting [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by tchesa** [comment]
I'd like to work on this

**Comment by jeyemwey** [comment]
I can do that :)
