### ISSUE TITLE
Request: catjam / vibecat

### ISSUE THREAD

**Issue by lollercopter** [jmhobbs/cultofthepartyparrot.com#523]
Catjam / Vibecat makes everything better.

https://knowyourmeme.com/memes/catjam-vibing-cat

https://tuckbot.tv/#/watch/joshy8

**Comment by lollercopter** [comment]
I finally got around to making it: https://i.imgur.com/SBA2xlo.gif

Can you add it to the collection? Maybe name it "vibepartycat" or something.

**Comment by jmhobbs** [comment]
Yeaaaah!

![partyvibecat](https://user-images.githubusercontent.com/115059/128546447-e17dc126-e954-48d1-9fe5-b88b2e23c3cd.gif)

**Comment by jmhobbs** [comment]
Yep! Thanks @zoidbergwill
