### ISSUE TITLE
Request: beer-parrot

### ISSUE THREAD

**Issue by ggentzke** [jmhobbs/cultofthepartyparrot.com#53]
Similar to other [beverage]-parrot and [food]-parrot gifs, I think a beer-parrot is absolutely in order!

e.g.: 
![coffeeparrot](https://cloud.githubusercontent.com/assets/14310/20406850/f39f6edc-acdc-11e6-9d9a-d5ca51466699.gif)

**Comment by jmhobbs** [comment]
But it would slosh out!

![Robotic Beer Holder](https://cloud.githubusercontent.com/assets/115059/20407109/95a4e142-acd5-11e6-8d6c-0e8b76461f2c.gif)

**Comment by kbvincent** [comment]
#58 Also includes Dark Beer Parrot

**Comment by jmhobbs** [comment]
Closing now that we have #57 and #58
