### ISSUE TITLE
Zip on cultofthepartyparrot.com does not contain all parrots

### ISSUE THREAD

**Issue by jgadelange** [jmhobbs/cultofthepartyparrot.com#559]
Yesterday I updated my slack emoji with the newest zip of parrots. But to my surprise for example the sneezy parrot is not available in the zip, but it is on the overview page.

**Comment by jmhobbs** [comment]
Oh man!  Don't know how I missed messing that up, I'll get it fixed and add a test.  Thank you for reporting it!
