### ISSUE TITLE
Ahem, Hanukkah Parrot? 

### ISSUE THREAD

**Issue by edwardsfriedman** [jmhobbs/cultofthepartyparrot.com#59]

**Comment by jmhobbs** [comment]
Thoughts on what that should look like? Party parrot with a driedel?  Menorah?

**Comment by edwardsfriedman** [comment]
I'm kvelling! thanks, @jmhobbs  

If there were a way to accommodate a spinning dreidel and a parrot, it would make my holiday!

**Comment by jmhobbs** [comment]
@edwardsfriedman please see #61 and give feedback, thanks!
