### ISSUE TITLE
JUMBOMOJI

### ISSUE THREAD

**Issue by adamburgess** [jmhobbs/cultofthepartyparrot.com#6]
Slack changed the sizes of emoji to 32x32!

> Ever feel regular-sized emoji aren't enough to express your inner :joy:? Us too. So we made JUMBOMOJI. Now, messages containing emoji only (up to 23 at a time) are displayed jumbo-sized. Regular terms and conditions may apply. If emoji have those. We feel like they probably don't. 

Any chance the .gif versions could be re-rendered at this insanely high resolution? :balloon:

**Comment by jmhobbs** [comment]
SHEER MADNESS.

Unfortunately, the source material isn't very big.

The original place that we came across the parrot was http://bukk.it/parrot.gif, which isn't any larger, and I haven't been able to find a hi-res alternative through googling.

I've redone a [single frame](http://cultofthepartyparrot.com/parrot.svg) for shirts and stickers, but not the rest.  If I get a chance, I want to play with making a few more frames then using [morphSVG](http://greensock.com/morphSVG) to animate it.

Ideas are welcome, as are leads to find the creator of the original gif.

**Comment by frankfarmer** [comment]
An animated svg version would make for a great http://gifpop.io/ submission

**Comment by oliviag** [comment]
I might be able to do this by hand when I have some downtime at work. I may just re-create it by rotoscoping the original video file.

@frankfarmer I'm actually looking into getting lenticular prints for another project right now. Don't know how interested @jmhobbs might be in selling cards or what have you, but you might get a better price (with a bit more work) going through another service like http://www.snapilypro.com/. I can report back with my findings if/when I use it!

**Comment by aendrew** [comment]
Can this be closed now that there's hi-rez versions on the site? It doesn't seem realistic to make each and every submission high-res — OR IS IT?

**Comment by jmhobbs** [comment]
Good point @aendrew, closing for now unless someone wants to convert them all.
