### ISSUE TITLE
Update Autonomous Parrot Background

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#608]
Autonomous Parrot has a solid background.  This should be cleaned up to use a transparent background.

![Autonomous Parrot](https://cultofthepartyparrot.com/parrots/hd/autonomousparrot.gif)

**Comment by LucianeFernandesRoque** [comment]
I want this issue, Its change background for transparente?

**Comment by LucianeFernandesRoque** [comment]
i open PR https://github.com/jmhobbs/cultofthepartyparrot.com/pull/610 can you assigne for me
