### ISSUE TITLE
Update Party Bug Background

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#609]
Party Bug has a solid background.  This should be cleaned up to use a transparent background.

![Party Bug](https://cultofthepartyparrot.com/guests/hd/bugparrot.gif)

**Comment by jmhobbs** [comment]
Sure thing, let me know when you have a PR up @rohitsinghind

**Comment by jmhobbs** [comment]
Sure thing @Bharadwajshivam28, never got a PR from Rohit afaict.  Thanks!

**Comment by Bharadwajshivam28** [comment]
ok @jmhobbs

**Comment by Bharadwajshivam28** [comment]
can your just drop that where is the party bug I cant find it

**Comment by jmhobbs** [comment]
It's actually called "bugparrot.gif"

https://github.com/jmhobbs/cultofthepartyparrot.com/blob/main/guests/hd/bugparrot.gif

**Comment by Bharadwajshivam28** [comment]
ok

**Comment by jmhobbs** [comment]
Fixed by #628, thanks @Bharadwajshivam28!

**Comment by Bharadwajshivam28** [comment]
> Fixed by #628, thanks @Bharadwajshivam28!

Thanks 👍
