### ISSUE TITLE
Update Database Parrot Background

### ISSUE THREAD

**Issue by jmhobbs** [jmhobbs/cultofthepartyparrot.com#612]
Database Parrot has a solid background. This should be cleaned up to use a transparent background.

![Database Parrot](https://cultofthepartyparrot.com/parrots/databaseparrot.gif)

**Comment by marianabeldi** [comment]
Hi! I can work on this issue

**Comment by jmhobbs** [comment]
Hey @marianabeldi, looks like this one is already being worked on in #617

**Comment by marianabeldi** [comment]
oh, sorry! I didn't see that one
