### ISSUE TITLE
Adding a Scroll to the Top Button to the website

### ISSUE THREAD

**Issue by smty2018** [jmhobbs/cultofthepartyparrot.com#647]
Want to add a scroll to the top button  for better UX

**Comment by jmhobbs** [comment]
Sounds good to me!

**Comment by JaySable82** [comment]
can i solve this issue?? Please assign it to me....

**Comment by RAJNIKANT1021** [comment]
can i solve this issue?? Please assign it to me....

**Comment by Sahil-Sharma06** [comment]
Please assign this task to me @smty2018

**Comment by katarisreelasya** [comment]
please assign me this issue i can do it...here is the sample code 

<!DOCTYPE html>
<html>
<head>
    <title>Simple Calculator</title>
    <style>
        #scrollUpBtn {
            display: none;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            border: none;
            outline: none;
            background-color: red;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 50%;
        }
    </style>
    <script>
        function add() {
            var operand1 = parseFloat(document.getElementById('operand1').value);
            var operand2 = parseFloat(document.getElementById('operand2').value);
            document.getElementById('result').value = operand1 + operand2;
        }

        function subtract() {
            var operand1 = parseFloat(document.getElementById('operand1').value);
            var operand2 = parseFloat(document.getElementById('operand2').value);
            document.getElementById('result').value = operand1 - operand2;
        }

        function multiply() {
            var operand1 = parseFloat(document.getElementById('operand1').value);
            var operand2 = parseFloat(document.getElementById('operand2').value);
            document.getElementById('result').value = operand1 * operand2;
        }

        function divide() {
            var operand1 = parseFloat(document.getElementById('operand1').value);
            var operand2 = parseFloat(document.getElementById('operand2').value);
            if (operand2 === 0) {
                document.getElementById('result').value = "Cannot divide by zero";
            } else {
                document.getElementById('result').value = operand1 / operand2;
            }
        }

        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("scrollUpBtn").style.display = "block";
            } else {
                document.getElementById("scrollUpBtn").style.display = "none";
            }
        }

        function scrollToTop() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
</head>
<body>
    <h2>Simple Calculator</h2>
    <input type="number" id="operand1" placeholder="Enter first number"><br><br>
    <input type="number" id="operand2" placeholder="Enter second number"><br><br>
    <button onclick="add()">Add</button>
    <button onclick="subtract()">Subtract</button>
    <button onclick="multiply()">Multiply</button>
    <button onclick="divide()">Divide</button><br><br>
    <input type="text" id="result" placeholder="Result" disabled>

    <button onclick="scrollToTop()" id="scrollUpBtn" title="Go to top">^</button>

</body>
</html>
