### ISSUE TITLE
Party CSS

### ISSUE THREAD

**Issue by WillMatthews** [jmhobbs/cultofthepartyparrot.com#651]
Party parrots are a bit of a staple at my work, much to the dismay of my boss (he is still a kākāpō fan though don't worry).
As my biggest act of defiance (so far) I party-parrotified the frontend of our product using using some CSS that I created. I have since decided to open source the CSS so that others can enjoy it too.

It is no parrot, but I hope it's somehow useful.

https://github.com/WillMatthews/party-css
https://jsfiddle.net/zxgphb4L/13/

**Comment by jmhobbs** [comment]
![It's beautiful....](https://github.com/user-attachments/assets/355d03e4-729b-45cd-b644-39ed0c10e54a)

**Comment by jmhobbs** [comment]
I'll add that as a link, thanks for sharing!
