### ISSUE TITLE
Request: Love-heart parrot

### ISSUE THREAD

**Issue by yamogi** [jmhobbs/cultofthepartyparrot.com#67]
Hi,

It would be awesome to have a parrot much like :ice_cream_parrot: except either holding or being the owner of a love heart. The heart could pulse / beat to make it stand out?

Thanks!

**Comment by francoislg** [comment]
Here is a quick one while you wait for a more elaborate, beating/pulsing one :)

![Heart Party Parrot](http://ppaas.herokuapp.com/partyparrot?overlay=http://www.heartyoursmile.co.uk/assets/images/hearts-dental-1.png&overlayWidth=10&overlayHeight=10&overlayOffsetX=9&overlayOffsetY=4) ([link](http://ppaas.herokuapp.com/partyparrot?overlay=http://www.heartyoursmile.co.uk/assets/images/hearts-dental-1.png&overlayWidth=10&overlayHeight=10&overlayOffsetX=9&overlayOffsetY=4))

Feel free to change the image :)

**Comment by yamogi** [comment]
@francoislg that's fantastic! Thank you very much!

**Comment by melinerunen** [comment]
@jmhobbs i think that we already have the love parrot. Can you close this issue or we need it for something else?

**Comment by melinerunen** [comment]
@jmhobbs #90 !!!
