### ISSUE TITLE
Ryan Gosling Won't Eat His Cereal Parrot.

### ISSUE THREAD

**Issue by acressie** [jmhobbs/cultofthepartyparrot.com#79]
Made this gosling-parrot that I'd like to contribute but don't appear to have permissions to submit.
Please include if you like!

![gosling-parrot](https://cloud.githubusercontent.com/assets/20261200/22050323/0e3c06ce-dd8e-11e6-85ff-47550eceaa29.gif)

**Comment by jmhobbs** [comment]
This is great!  What would the filename/slack code be?  `ryangoslingparrot.gif`?

**Comment by acressie** [comment]
Haha thanks mate. Yeah sounds good to me :-)
