### ISSUE TITLE
Can Party Parrots be sad?

### ISSUE THREAD

**Issue by glentakahashi** [jmhobbs/cultofthepartyparrot.com#9]
Not sure if Party Parrots have time to be sad when they're partying to much, but if they can, it might be nice to have a sad parrot.

**Comment by jmhobbs** [comment]
Party parrot sunny all the time always!

Honestly though, I'm not sure how I would add it, someone with better graphics ability than me would have to edit that beak into a frown.

In the meantime, may I recommend ![Bored Parrot](http://cultofthepartyparrot.com/parrots/boredparrot.gif) or ![Goth Parrot](http://cultofthepartyparrot.com/parrots/gothparrot.gif) as the closest alternatives?

**Comment by glentakahashi** [comment]
I was thinking of maybe a party teardrop falling down. I'll probably do it
tonight after work and make a PR.

**Comment by glentakahashi** [comment]
https://github.com/jmhobbs/cultofthepartyparrot.com/pull/10
