### ISSUE TITLE
HD Parrot?

### ISSUE THREAD

**Issue by lucymhdavies** [jmhobbs/cultofthepartyparrot.com#94]
Somebody at work found this

http://giphy.com/gifs/producthunt-party-parrot-parrots-l3q2zVr6cu95nF6O4

![HD Parrot](http://i.giphy.com/l3q2zVr6cu95nF6O4.gif)

**Comment by francoislg** [comment]
It's missing some frames, and it is available here:

https://ppaas.herokuapp.com/partyparrot/mega

**Comment by lucymhdavies** [comment]
ah

![more frames](https://ppaas.herokuapp.com/partyparrot/mega)

Yes, this one is better

**Comment by jmhobbs** [comment]
For sure, as a link off the main like the SVG?  Also, any word on the origin, the reddit post was deleted afaik?

**Comment by thibautRe** [comment]
There is actually quite a lot of HD parrots

![sadparrot](https://i.redd.it/j1sd2s6u9y3y.gif)

If you go to [this link](https://www.reddit.com/r/PartyParrot/comments/5l5nya/12_days_of_partyparrot_day_12/) and scroll a bit down you will find them all.

![](https://i.redd.it/kb7wlwjr9y3y.gif)
![](https://i.redd.it/st4ls2uecr3y.gif)

**Comment by lucymhdavies** [comment]
Oh wow. If we can find the right person/people to credit, it would be fantastic to get these in the repo.

**Comment by jmhobbs** [comment]
I messaged `_korbendallas_` on Reddit to see if they had a lead on creator(s)

**Comment by jmhobbs** [comment]
So, we are good to use HD parrot 👍 

I'm not sure how we should put those up.  As a separate zip?  As a folder within the zip?

Thoughts?

**Comment by lucymhdavies** [comment]
Storing the HD versions in their native resolution somewhere in the repo is a good idea.

I was actually thinking we could scale them down to 128x128 (slack's max resolution for emojis), and replace any of the small ones that match.

Thoughts?

**Comment by jmhobbs** [comment]
I'm not sure 😕  there is a charm to the classic pixel-ness of them, I'd like to at least offer them both.

Maybe put them both in the zip, suffix the HD ones with `-hd.gif` and then indicate on the web page that HD versions exist for certain ones?   Or vice-versa, mark the lower res ones with `-original.gif` or something.

**Comment by lucymhdavies** [comment]
One or the other. I've no preference either way.

**Comment by jmhobbs** [comment]
Closed by #97

**Comment by korbendallas-reddit** [comment]
Hey, I made these!

More can be found here:

https://www.reddit.com/r/PartyParrot/wiki/hdpartyparrots
