### ISSUE TITLE
Party Parrot wants your soul

### ISSUE THREAD

**Issue by 8-uh** [jmhobbs/cultofthepartyparrot.com#99]
http://codepen.io/codevinsky/full/LWprYo/
chrome required
put your headphones on...
(slightly nsfw audio)

**Comment by jmhobbs** [comment]
O_O

**Comment by dnguyenchevy** [comment]
Please no.

**Comment by jmhobbs** [comment]
I'm not sure what to do with this.  Page link?  I was also thinking a `console.log` could be cool, since codepen would be enjoyed by developers.

```javascript
console.log("PARTY PARROT WANTS YOUR SOUL: http://codepen.io/codevinsky/full/LWprYo/");
```

Thoughts?
